### ISSUE TITLE
Default settings when wrapping an app

### ISSUE THREAD

**Issue by BBokdam** [msintuneappsdk/intune-app-wrapping-tool-android#10]
Hi,

I was wondering what is happening when you wrap an app with the tool. The reason is that I have app from the store that is working fine when we installed it from the PlayStore. 

After wrapping the app without any policies the app stops working when we installed it from Intune.

So the question is what happens with the APK file when it's wrapped.

Thank you for the answer.

Barry

**Comment by msintuneappsdk** [comment]
Hi @BBokdam, we missed addressing your issue. Are you still working with the Intune App Wrapping Tool? Is this still an issue you are having with the latest release? If so, please provide some more info. Are you working with a native app? Who is the Intune customer building the app, and/or the app is being provided for?

When an apk is wrapped by the Intune App Wrapping Tool for Android, essentially it changes the behavior of your in-house Android apps by restricting features of the app without you having to change the code of the app itself (there's some decompiling and recompiling that happens). Your app now becomes enabled for app protection policies through Intune.

**Comment by BBokdam** [comment]
Hi @msintuneappsdk ,
THe problem we had is solved by the supplier from the application.

Thank you for replying.

**Comment by msintuneappsdk** [comment]
Thanks. Closing issue.
