### ISSUE TITLE
wrapped app (android )  is getting crashed while opening

### ISSUE THREAD

**Issue by Abhijith-G** [msintuneappsdk/intune-app-wrapping-tool-android#11]
HI There,

Wrapped apk is crashing while opening the app. Unwrapped apk is working fine. The app is developed in Xamarin.
PFB device log also.

Could you please help on this ASAP 
![screenshot_2018-02-27-12-05-20-599_com miui bugreport](https://user-images.githubusercontent.com/28953577/36715424-296093c6-1bbc-11e8-93d4-e2deab0179dc.png)

**Comment by msintuneappsdk** [comment]
@Abhijith-G I've added you to a preview build of the wrapper, please try wrapping using the build and report back here on if it fixed your issue.

**Comment by msintuneappsdk** [comment]
Closing issue as this customer has functioning apps with Xamarin.
