### ISSUE TITLE
Intune app wrapping tool for Android doesn't generate output apk file - No errors

### ISSUE THREAD

**Issue by sagrsk** [msintuneappsdk/intune-app-wrapping-tool-android#12]
Hi,

I have been trying to wrap an LOB app. Below is the verbose comments after the command is run.

PS C:\IntuneAppWrapping> Invoke-AppWrappingTool -InputPath C:\Sagar\1-Name\app-UNILEVER-V-1.2.5-release.apk -OutputPath C:\Users\ssagar\Desktop\1name\output.apk -KeyStorePath "C:\Program Files (x86)\Java\jre1.8.0_161\bin\unile
ver_keystore.jks" -KeyAlias unilever_keystore -SigAlg SHA1 -Verbose

cmdlet Invoke-AppWrappingTool at command pipeline position 1
Supply values for the following parameters:
KeyStorePassword: ***************
KeyPassword: ***************
Application wrapping in progress. App Wrapping Tool Version: 1.0.2116.2
Using Apktool 2.3.0 on app-UNILEVER-V-1.2.5-release.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\ssagar\AppData\Local\Temp\IntuneAppWrappingTool-13012691652445985905\framework\1.apk
Regular manifest package...
Decoding file-resources...
Win version: 0x3ad7000a = 987168778 (Windows Vista)
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Using Apktool 2.3.0 on IntuneAppBase.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\ssagar\AppData\Local\Temp\IntuneAppWrappingTool-13012691652445985905\framework\1.apk
Regular manifest package...
Decoding file-resources...
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
PS C:\IntuneAppWrapping>

After the "Copying original files" message it doesn't say anything and goes back to command prompt.

Please help, this is urgent.

**Comment by msintuneappsdk** [comment]
@jason8232590 @sagrsk Are you working with a native Android app? Are you using the latest version of the app wrapping tool? Does this app work on the device without being wrapped? Please send us an email to msintuneappsdk@microsoft.com so we get more private details from you.

**Comment by jason8232590** [comment]
I figured out the root cause . You need to degrade your JDK to 1.8.0 rather than use 1.9.

**Comment by sagrsk** [comment]
How degrading JDK works here?

**Comment by sagrsk** [comment]
In fact, Java in machine is jre1.8.0_161.

**Comment by OmarHassan25** [comment]
Dear, have you figured out the reason? i have the same issue
