### ISSUE TITLE
Failed to package app.         com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to update this app's supported SDK versions.

### ISSUE THREAD

**Issue by enlivenaman** [msintuneappsdk/intune-app-wrapping-tool-android#14]
Application wrapping in progress. App Wrapping Tool Version: 1.0.2116.2
Using Apktool 2.3.0 on app-release-unsigned.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\1000213\AppData\Local\Temp\IntuneAppW
rappingTool-7696559053548400319\framework\1.apk
Regular manifest package...
Decoding file-resources...
Win version: 0x1db10106 = 498139398 (Windows Vista)
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Using Apktool 2.3.0 on IntuneAppBase.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\1000213\AppData\Local\Temp\IntuneAppW
rappingTool-7696559053548400319\framework\1.apk
Regular manifest package...
Decoding file-resources...
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Checking whether resources has changed...
Building resources...
Loading resource table...
Checking whether resources has changed...
Building resources...
Loading resource table...
Checking whether resources has changed...
Building resources...
Loading resource table...
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed
to update this app's supported SDK versions.
                com.microsoft.intune.mam.apppackager.utils.YamlManifestUtils.upd
ateAppSupportedSdkRange(YamlManifestUtils.java:337)
                com.microsoft.intune.mam.apppackager.v2.V2WrapperAgent.wrapManif
est(V2WrapperAgent.java:86)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(A
bstractWrapperAgent.java:69)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppP
ackager.java:135)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(P
ackagerMain.java:200)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerM
ain.java:56)
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: This ap
p's target SDK is above the MAM target SDK. Please upgrade to the newest version
 of the App Wrapping Tool.
                com.microsoft.intune.mam.apppackager.utils.YamlManifestUtils.upd
ateAppSupportedSdkRange(YamlManifestUtils.java:318)
                com.microsoft.intune.mam.apppackager.v2.V2WrapperAgent.wrapManif
est(V2WrapperAgent.java:86)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(A
bstractWrapperAgent.java:69)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppP
ackager.java:135)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(P
ackagerMain.java:200)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerM
ain.java:56)
The application could not be wrapped.

**Comment by bhumin3i** [comment]
@msintuneappsdk  same issue i'm facing please help me on this .... :(

**Comment by alexlobanov** [comment]
@msintuneappsdk same issue there. 

If you have any plans / timelines to support latest versions of the Android SDK?

 Our company develop mobile apps based on Xamarin.Forms framewokrs, and most of libraries for Android now require **Android.Support.Core > 27.0.2 that require - monodroid8.1**

**Comment by oh-blah-de** [comment]
Same issue.   Concerned that this project is dead.

**Comment by msintuneappsdk** [comment]
@enlivenaman @bhumin3i @oh-blah-de The version 1.0.2116.2 (latest release) of the wrapping tool supports Android apps targeted up to Android API 26. Support for Android P (API 28) will be available shortly after Android P is released.   

@alexlobanov For enabling Xamarin based apps with Microsoft Intune, our guidance is to use the [Xamarin Bindings](https://github.com/msintuneappsdk/intune-app-sdk-xamarin).

**Comment by rohanthakran** [comment]
Smaling smali folder into classes.dex...
Checking whether sources has changed...
Smaling smali_classes2 folder into classes2.dex...
Checking whether sources has changed...
Smaling smali_classes3 folder into classes3.dex...
Checking whether sources has changed...
Smaling smali_classes4 folder into classes4.dex...
Checking whether resources has changed...
Building resources...
aapt2 compile command ran:
[C:\Users\Admin\AppData\Local\Temp\brut_util_Jar_156717545870992829713273642867564319989.tmp, compile, --dir, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-4266589796754228321\sourceApk\res, --legacy, -o, C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-4266589796754228321\sourceApk\build\resources.zip]
C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-4266589796754228321\sourceApk\res\layout\number_picker_material.xml:2: error: resource android:style/TextAppearance.MisspelledSuggestion is private.
error: failed linking file resources.
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:157)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:104)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:205)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:85)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:238)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:60)
