### ISSUE TITLE
The application could not be wrapped.         java.lang.NullPointerException                 brut.androlib.res.data.value.ResStyleValue.serializeToResValuesX ml

### ISSUE THREAD

**Issue by enlivenaman** [msintuneappsdk/intune-app-wrapping-tool-android#15]
@msintuneappsdk I'm using intune-app-wrapping-tool-android version 1.0.1933.1 and getting below issue: 
The application could not be wrapped.
        java.lang.NullPointerException
                brut.androlib.res.data.value.ResStyleValue.serializeToResValuesX
ml(ResStyleValue.java:58)
                brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibR
esources.java:516)
                brut.androlib.res.AndrolibResources.decode(AndrolibResources.jav
a:267)
                brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
                brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.decode
APK(APKToolWrapper.java:106)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppP
ackager.java:77)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(P
ackagerMain.java:198)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerM
ain.java:56)

**Comment by msintuneappsdk** [comment]
Hi @enlivenaman, we missed addressing your issue. are you still working with the Intune App Wrapping Tool? Is this still an issue you are having with the latest release? If so, please provide some more info. Are you working with a native app? What is the targeted Android SDK version set for this app? Who is the Intune customer building the app, and/or the app is being provided for?
