### ISSUE TITLE
Wrapping with ADAL Library in App

### ISSUE THREAD

**Issue by karlbarek** [msintuneappsdk/intune-app-wrapping-tool-android#18]
We are currently running into the issue:
After wrapping and we have deployed into our Intune store. Then we installed app from the Comp Portal App. After launching the app, it asks Microsoft login and after successfully logging in the app begins to launch and then shows a pop up with **This Application not set up for you and contact your IT Administrator** error. 
The app does use the android ADAL library and is a dependency within the gradle file. Are apps that use ADAL allowed to be wrapped? I haven't come across any documentation discussing this.

Thanks, 

Karl

**Comment by aanavath** [comment]
You need to target policy to the app through the Azure console blade for Intune app protection or you will see the ‘This app has not been set up for you to use. Contact your IT administrator for help.’

**Comment by aanavath** [comment]
@karlbarek Let us know if you are still experiencing this issue, if not, we can close this item.

**Comment by karlbarek** [comment]
@aanavath Your suggestion solved our issue. Thanks again.
