### ISSUE TITLE
Wrapped App Crashes On Start

### ISSUE THREAD

**Issue by CppBunny** [msintuneappsdk/intune-app-wrapping-tool-android#19]
I correctly wrapped and signed the .apk but the app crashes instantly upon launch with the following message:

FATAL EXCEPTION: GoogleApiHandler
java.lang.SecurityException
at android.os.Parcel.readException(Parcel.java:1959)
at android.os.Parcel.readException(Parcel.java:1905)
at com.google.android.gms.common.internal.zzay.zza(Unknown Source:35)
at com.google.android.gms.common.internal.zzd.zza(Unknown Source:112)
at com.google.android.gms.common.api.internal.zzbw.run(Unknown Source:43)
at android.os.Handler.handleCallback(Handler.java:789)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)

Noticed some people saying that this is related to google play services and that this has apparently been fixed but it doesn't seem that way.

What's wrong here?

**Comment by aanavath** [comment]
Hi @nnvt. What version of the wrapping tool are you using? Are you working with a native Android app or one built with Xamarin/Cordova or something else? Do you see a trend with this being reproduced on a specific device? Does the app launch without the Intune app wrapping process applied?

**Comment by thomasvsundert** [comment]
FYI this was resolved by updating the intune SDK to the latest version

**Comment by aanavath** [comment]
@nnvt Please try using the latest app wrapping tool release and let us know if you are still experiencing the issue. If not, we can close this item.

**Comment by ryandegruyter** [comment]
We are experiencing the same issue all of sudden. Everything was working fine until tuesday.

Context

- Latest company portal app
- Latest Intune wrapper version
- Cordova application with push plugin

**Comment by msintuneappsdk** [comment]
@ryandegruyter Are you still experiencing this issue? Do you see a trend with only being reproduced on a specific device? Assuming the app is launching without being wrapped?
