### ISSUE TITLE
Wrapped app crashing in device without giving any appropriate error message.

### ISSUE THREAD

**Issue by sanjog152** [msintuneappsdk/intune-app-wrapping-tool-android#2]
![screenshot_2016-10-21-11-28-00](https://cloud.githubusercontent.com/assets/3949468/19588243/0888d75e-9782-11e6-8ca8-b265a4c71fdc.png)

When I am opening my app it will show this message and when I click on _OK_ button **App crashes without giving any proper message**

**Comment by oydang** [comment]
Hi @sanjog152 can you please send me (olivia.dang@microsoft.com) the Company Portal logs? Thank you.

**Comment by sanjog152** [comment]
@oydang I have already sent you a mail regarding the android wrap issue with wrap log file and APK file.

**Comment by sanjog152** [comment]
@oydang @msintuneappsdk Any update on this. I have already sent you the APK as well as log files via mail.

**Comment by sanjog152** [comment]
@oydang I am waiting for the solution.

**Comment by oydang** [comment]
@sanjog152 I have **not** received an email from you with the .apk. Please resend to olivia.dang@microsoft.com or msintuneappsdk@microsoft.com.

**Comment by sanjog152** [comment]
@oydang @msintuneappsdk Again sent you from email ID **sanjog@wizergos.com**. Please check your spam folder as well.

**Comment by sanjog152** [comment]
No response from Microsoft. That's why closing this issue.
