### ISSUE TITLE
Android wrapping failed with libpng error

### ISSUE THREAD

**Issue by quantumarun** [msintuneappsdk/intune-app-wrapping-tool-android#23]
Hi Team,
While wrapping the apk using Wrapping tool i am getting below error. Original apk is working fine. Can you please help out here.

WRN Application wrapping in progress. App Wrapping Tool Version: 1.0.2501.1
DBG Begin Packaging: <PATH>\app-development-debug_test1.apk
DBG [APKTool] Begin decoding APK file: <PATH>\app-development-debug_test1.apk
INF Using Apktool 2.3.4 on app-development-debug_test1.apk
INF Loading resource table...
INF Decoding AndroidManifest.xml with resources...
INF Loading resource table from file: <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\framework\1.apk
INF Regular manifest package...
INF Decoding file-resources...
VRB Win version: 0x42ee000a = 1122893834 (Windows Vista)
INF Decoding values */* XMLs...
INF Baksmaling classes.dex...
INF Copying assets and libs...
INF Copying unknown files...
INF Copying original files...
DBG [APKTool] Finish decoding APK file: <PATH>\app-development-debug_test1.apk
DBG [APKTool] Begin decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\lib\IntuneAppBase.apk
INF Using Apktool 2.3.4 on IntuneAppBase.apk
INF Loading resource table...
INF Decoding AndroidManifest.xml with resources...
INF Loading resource table from file: <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\framework\1.apk
INF Regular manifest package...
INF Decoding file-resources...
INF Decoding values */* XMLs...
INF Baksmaling classes.dex...
INF Copying assets and libs...
INF Copying unknown files...
INF Copying original files...
DBG [APKTool] Finish decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\lib\IntuneAppBase.apk
DBG [WrapperAgent][Begin] Updating app manifest.
DBG [Manifest] Begin merging manifests.
DBG [Manifest] Finish merging manifests.
DBG [WrapperAgent][End] Updating app manifest.
DBG [WrapperAgent][Begin] Updating app resources.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_cab_background_top_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_divider_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_focused_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_longpressed_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_pressed_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_pressed_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_selector_disabled_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_list_selector_disabled_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_popup_background_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_scrubber_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_switch_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_tab_indicator_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_textfield_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_textfield_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_low_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-ldrtl-hdpi-v17/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-ldrtl-mdpi-v17/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-ldrtl-xhdpi-v17/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-ldrtl-xxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-ldrtl-xxxhdpi-v17/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_cab_background_top_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_divider_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_focused_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_longpressed_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_pressed_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_pressed_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_selector_disabled_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_list_selector_disabled_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_popup_background_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_scrubber_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_switch_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_tab_indicator_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_textfield_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_textfield_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_low_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_divider_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_focused_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_longpressed_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_pressed_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_pressed_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_list_selector_disabled_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_popup_background_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_switch_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_textfield_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_ab_share_pack_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_cab_background_top_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_divider_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_focused_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_longpressed_holo.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_pressed_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_pressed_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_dark.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_list_selector_disabled_holo_light.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_menu_hardkey_panel_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_popup_background_mtrl_mult.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_scrubber_primary_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_scrubber_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_switch_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_textfield_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_textfield_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_textfield_search_activated_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/abc_textfield_search_default_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00001.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxxhdpi-v4/abc_btn_switch_to_on_mtrl_00012.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxxhdpi-v4/abc_spinner_mtrl_am_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxxhdpi-v4/abc_switch_track_mtrl_alpha.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxxhdpi-v4/abc_tab_indicator_mtrl_alpha.9.png.
DBG [Res][Begin] Merging app resources.
DBG [Res][Begin] Merging app resources of type Animator.
DBG [Res][End] Merging app resources of type Animator
DBG [Res][Begin] Merging app resources of type Anim.
DBG [Res][End] Merging app resources of type Anim
DBG [Res][Begin] Merging app resources of type Color.
DBG [Res][End] Merging app resources of type Color
DBG [Res][Begin] Merging app resources of type Drawable.
DBG [Res][End] Merging app resources of type Drawable
DBG [Res][Begin] Merging app resources of type MipMap.
DBG [Res][End] Merging app resources of type MipMap
DBG [Res][Begin] Merging app resources of type Layout.
DBG [Res][End] Merging app resources of type Layout
DBG [Res][Begin] Merging app resources of type Menu.
DBG [Res][End] Merging app resources of type Menu
DBG [Res][Begin] Merging app resources of type Raw.
DBG [Res][End] Merging app resources of type Raw
DBG [Res][Begin] Merging app resources of type Values.
DBG [Res][End] Merging app resources of type Values
DBG [Res][Begin] Merging app resources of type Xml.
DBG [Res][End] Merging app resources of type Xml
INF Checking whether resources has changed...
INF Building resources...
WRN libpng error: Not a PNG file
WRN ERROR: Failure processing PNG image <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\res\drawable\<filename>.png
DBG [Res][End] Merging app resources.
DBG [WrapperAgent][End] Updating app resources.
ERR Failed to package app.
	com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
	brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [<PATH>\AppData\Local\Temp\brut_util_Jar_4764167264544704433.tmp, p, --forced-package-id, 127, --rename-manifest-package, AppPackager.AppBase, --no-version-vectors, -F, <PATH>\AppData\Local\Temp\APKTOOL2244213982667881482.tmp, -0, arsc, -I, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\framework\1.apk, -S, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\res, -M, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\AndroidManifest.xml]
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:503)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:138)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
	brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [<PATH>\AppData\Local\Temp\brut_util_Jar_4764167264544704433.tmp, p, --forced-package-id, 127, --rename-manifest-package, AppPackager.AppBase, --no-version-vectors, -F, <PATH>\AppData\Local\Temp\APKTOOL2244213982667881482.tmp, -0, arsc, -I, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\framework\1.apk, -S, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\res, -M, <PATTH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\AndroidManifest.xml]
		brut.androlib.res.AndrolibResources.aapt1Package(AndrolibResources.java:574)
		brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:597)
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:138)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
	brut.common.BrutException: could not exec (exit code = 1): [<PATH>\AppData\Local\Temp\brut_util_Jar_4764167264544704433.tmp, p, --forced-package-id, 127, --rename-manifest-package, AppPackager.AppBase, --no-version-vectors, -F, <PATH>\AppData\Local\Temp\APKTOOL2244213982667881482.tmp, -0, arsc, -I, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\framework\1.apk, -S, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\res, -M, <PATH>\AppData\Local\Temp\IntuneAppWrappingTool-8264194613439799937\sourceApk\AndroidManifest.xml]
		brut.util.OS.exec(OS.java:98)
		brut.androlib.res.AndrolibResources.aapt1Package(AndrolibResources.java:570)
		brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:597)
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:138)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
ERR Failed to load app resource table.
WRN Verbose logs can be found at: <PATH>\AppData\Local\Temp\IntuneAppWrappingToolLog_20190312_163806.txt.
ERR The application could not be wrapped.

**Comment by rygo-msft** [comment]
Hi @quantumarun,
Can you provided a few additional details about your app?
- Does this app wrap successfully with previous versions of App Wrapper?
- What type of PNG is is the file that is failing? Is it a regular PNG or .9.PNG?
- What build-tools version is the app built with?
- Is the app using any of the Android-Q beta build tools that were recently released?
- Would you be willing the privately share the apk (or a sample apk that reproduces the same issue?)

**Comment by leonzhuyihong** [comment]
I got same error which said "Failed to load app resource table"

**Comment by quantumarun** [comment]
Hi @rygo-msft 
Answers Below:
Does this app wrap successfully with previous versions of App Wrapper? - _Wrapping FirstTime. So NA_
What type of PNG is is the file that is failing? Is it a regular PNG or .9.PNG? _Regular PNG_
What build-tools version is the app built with? _27.0.3_
Is the app using any of the Android-Q beta build tools that were recently released? _No_
Would you be willing the privately share the apk (or a sample apk that reproduces the same issue?) _I will not be able to share the apk._

**Comment by rygo-msft** [comment]
Version 1.0.2554.2 has an update to AAPT2 which may fix the issue.
Please try with the latest wrapper and let us know if this resolves the issue.
