### ISSUE TITLE
Cannot wrap application that uses Jetpack Navigation

### ISSUE THREAD

**Issue by lazarflorian** [msintuneappsdk/intune-app-wrapping-tool-android#24]
Hello, 

I am trying to wrap an APK file using build 1.0.2501.1, but I encountered the following error:

`Using Apktool 2.3.4 on btmrr_mobile_unsignedRelease_2.0.19.2.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\framework\1.apk
Regular manifest package...
Decoding file-resources...
Win version: 0x3839000a = 943259658 (Windows Vista)
Decoding values */* XMLs...
null reference: m1=0x01000001(reference), m2=0x7f030001(reference)
null reference: m1=0x01000002(reference), m2=0x7f030002(reference)
null reference: m1=0x01000001(reference), m2=0x00000089(string)
null reference: m1=0x01000001(reference), m2=0x00000088(string)
null reference: m1=0x01000001(reference), m2=0x7f1200c7(reference)
null reference: m1=0x01000002(reference), m2=0x7f120131(reference)
null reference: m1=0x01000003(reference), m2=0x7f12013c(reference)
null reference: m1=0x01000004(reference), m2=0x7f12012a(reference)
null reference: m1=0x01000005(reference), m2=0x7f12009a(reference)
null reference: m1=0x01000006(reference), m2=0x7f12010a(reference)
null reference: m1=0x01000007(reference), m2=0x7f120124(reference)
null reference: m1=0x01000001(reference), m2=0x7f1200c8(reference)
null reference: m1=0x01000002(reference), m2=0x7f120132(reference)
null reference: m1=0x01000003(reference), m2=0x7f12013d(reference)
null reference: m1=0x01000004(reference), m2=0x7f12012b(reference)
null reference: m1=0x01000005(reference), m2=0x7f12009b(reference)
null reference: m1=0x01000006(reference), m2=0x7f12010b(reference)
null reference: m1=0x01000007(reference), m2=0x7f120125(reference)
null reference: m1=0x01000001(reference), m2=0x7f090000(reference)
null reference: m1=0x01000002(reference), m2=0x7f090001(reference)
null reference: m1=0x01000003(reference), m2=0x7f090002(reference)
Baksmaling classes.dex...
Baksmaling classes2.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Using Apktool 2.3.4 on IntuneAppBase.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\framework\1.apk
Regular manifest package...
Decoding file-resources...
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Checking whether resources has changed...
Building resources...
**invalid resource directory name: C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\sourceApk\res navigation**
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:143)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
        brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_8137749940845474402.tmp,
 p, --forced-package-id, 127, --rename-manifest-package, AppPackager.AppBase, --no-version-vectors, -F, C:\Users\admin\AppData\Local\Temp\APKTOOL642163453686193419.tmp, -0, arsc, -I, C:\Users\admin\AppData\
Local\Temp\IntuneAppWrappingTool-214700656370201489\framework\1.apk, -S, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\sourceApk\res, -M, C:\Users\admin\AppData\Local\Temp\Intun
eAppWrappingTool-214700656370201489\sourceApk\AndroidManifest.xml]
                brut.androlib.Androlib.buildResourcesFull(Androlib.java:503)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:138)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
        brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_8137749940845474402.tmp, p, --forced-package-id, 127, --r
ename-manifest-package, AppPackager.AppBase, --no-version-vectors, -F, C:\Users\admin\AppData\Local\Temp\APKTOOL642163453686193419.tmp, -0, arsc, -I, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-
214700656370201489\framework\1.apk, -S, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\sourceApk\res, -M, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-2147006563702014
89\sourceApk\AndroidManifest.xml]
                brut.androlib.res.AndrolibResources.aapt1Package(AndrolibResources.java:574)
                brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:597)
                brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:138)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
        brut.common.BrutException: could not exec (exit code = 1): [C:\Users\admin\AppData\Local\Temp\brut_util_Jar_8137749940845474402.tmp, p, --forced-package-id, 127, --rename-manifest-package, AppPackag
er.AppBase, --no-version-vectors, -F, C:\Users\admin\AppData\Local\Temp\APKTOOL642163453686193419.tmp, -0, arsc, -I, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\framework\1.ap
k, -S, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\sourceApk\res, -M, C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingTool-214700656370201489\sourceApk\AndroidManifest.xml]
                brut.util.OS.exec(OS.java:98)
                brut.androlib.res.AndrolibResources.aapt1Package(AndrolibResources.java:570)
                brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:597)
                brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:138)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:96)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:113)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
Failed to load app resource table.
Verbose logs can be found at: C:\Users\admin\AppData\Local\Temp\IntuneAppWrappingToolLog_20190321_140945.txt.`

Note: I am using the new Android Jetpack Navigation ([url](https://developer.android.com/guide/navigation/)), hence the navigation folder under res.

Prior to using the Jetpack Navigation I was able to wrap the app successfully.

**Comment by rygo-msft** [comment]
This should be resolved in 1.0.2554.2
We now use AAPT2 which has support for the new navigation resource type

**Comment by lisleyanne20** [comment]
Hi, 
I am also trying to wrap an apk. I am using 1.0.2554.2. Please see error below:


Application wrapping in progress. App Wrapping Tool Version: 1.0.2554.2
Using Apktool 2.4.0 on Signed.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\framework\1.apk
Regular manifest package...
Decoding file-resources...
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Using Apktool 2.4.0 on IntuneAppBase.apk
Loading resource table...
Decoding AndroidManifest.xml with resources...
Loading resource table from file: C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\framework\1.apk
Regular manifest package...
Decoding file-resources...
Decoding values */* XMLs...
Baksmaling classes.dex...
Copying assets and libs...
Copying unknown files...
Copying original files...
Checking whether resources has changed...
Building resources...
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:147)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
        brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\LISLEY~1.HIN\AppData\Local\Temp\brut_util_Jar_6059336318897086006.tmp, compile, --dir, C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\sourceApk\res, --legacy, -o, C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\sourceApk\build\resources.zip]
                brut.androlib.Androlib.buildResourcesFull(Androlib.java:503)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:142)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
        brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\LISLEY~1.HIN\AppData\Local\Temp\brut_util_Jar_6059336318897086006.tmp, compile, --dir, C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\sourceApk\res, --legacy, -o, C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\sourceApk\build\resources.zip]
                brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:362)
                brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:601)
                brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:142)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
        brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\LISLEY~1.HIN\AppData\Local\Temp\brut_util_Jar_6059336318897086006.tmp, compile, --dir, C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\sourceApk\res, --legacy, -o, C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingTool-6256776938999099425\sourceApk\build\resources.zip]
                brut.util.OS.exec(OS.java:98)
                brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:358)
                brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:601)
                brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:142)
                com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
                com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
Failed to load app resource table.
Verbose logs can be found at: C:\Users\LISLEY~1.HIN\AppData\Local\Temp\IntuneAppWrappingToolLog_20190626_163817.txt.
The application could not be wrapped.
