### ISSUE TITLE
Android MAM application unable to identify deactivated AD account

### ISSUE THREAD

**Issue by quantumarun** [msintuneappsdk/intune-app-wrapping-tool-android#26]
Hi Team,
I had used Wrapping tool to wrap an android application for MAM and deployed to Intune Portal. The application works fine and does display AD authentication screen for verification on first launch and plus if we deploy any new MAM policy it works. But if AD account is deactivate then the MAM policy do not verify this and users are able to use the application thus violating the rule of MAM and revoking application access.

Can you please help us on this?

**Comment by msintuneappsdk** [comment]
Hi @quantumarun, we will follow up with you via email.
