### ISSUE TITLE
Failed to load app resource table

### ISSUE THREAD

**Issue by tarunchopra** [msintuneappsdk/intune-app-wrapping-tool-android#29]
1. Downloaded the latest wrapping tool
2. App is native Android App - https://github.com/OfficeDev/Interop-REST-Mail-Contacts-Calendar-Sample/tree/master/Android/MeetingManagerAndroid
3. .apk and logs are attached for reference.

ERR Failed to package app.
	com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.

[IntuneAppWrappingToolLog_20190510_150213.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/3168249/IntuneAppWrappingToolLog_20190510_150213.txt)

Convert this to .apk
[app-debug.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/3168251/app-debug.txt)

**Comment by rygo-msft** [comment]
This is appears to be the same as #27.
Please try using a 64-bit JVM as mentioned in the work around for that issue.

**Comment by aaryamanc** [comment]
Thanks @rygo-msft, that resolved the issue.

**Comment by tarunchopra** [comment]
Thanks @rygo-msft . That resolved the issue.

**Comment by rohanthakran** [comment]
C:\Users\Admin\AppData\Local\Temp\IntuneAppWrappingTool-13011381213506065050\sourceApk\res\layout\number_picker_material.xml:2: error: resource android:style/TextAppearance.Material.NumberPicker is private.
error: failed linking file resources.
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.  @rygo-msft
