### ISSUE TITLE
can not Wrap LOB android app

### ISSUE THREAD

**Issue by mfekry** [msintuneappsdk/intune-app-wrapping-tool-android#30]
I have the apk file for LOB application I cannot do wrapping as per below errors
WRN Application wrapping in progress. App Wrapping Tool Version: 1.0.2554.2
DBG Begin Packaging: D:\BM\BanqueMisr.apk
DBG [APKTool] Begin decoding APK file: D:\BM\BanqueMisr.apk
INF Using Apktool 2.4.0 on BanqueMisr.apk
INF Loading resource table...
INF Decoding AndroidManifest.xml with resources...
INF Loading resource table from file: C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\framework\1.apk
INF Regular manifest package...
INF Decoding file-resources...
VRB Win version: 0x4563000a = 1164115978 (Windows Vista)
INF Decoding values */* XMLs...
INF Baksmaling classes.dex...
INF Copying assets and libs...
INF Copying unknown files...
INF Copying original files...
DBG [APKTool] Finish decoding APK file: D:\BM\BanqueMisr.apk
DBG [APKTool] Begin decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\lib\IntuneAppBase.apk
INF Using Apktool 2.4.0 on IntuneAppBase.apk
INF Loading resource table...
INF Decoding AndroidManifest.xml with resources...
INF Loading resource table from file: C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\framework\1.apk
INF Regular manifest package...
INF Decoding file-resources...
INF Decoding values */* XMLs...
INF Baksmaling classes.dex...
INF Copying assets and libs...
INF Copying unknown files...
INF Copying original files...
DBG [APKTool] Finish decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\lib\IntuneAppBase.apk
DBG [WrapperAgent][Begin] Updating app manifest.
DBG [Manifest] Begin merging manifests.
DBG [Manifest] Finish merging manifests.
INF [Yaml] Input app's minimum API level was raised to MAM minimum API level: 19
INF [Yaml] Updating API level for minSdkVersion to 19.
DBG [WrapperAgent][End] Updating app manifest.
DBG [WrapperAgent][Begin] Updating app resources.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/common_google_signin_btn_text_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_low_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_low_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-hdpi-v4/notification_bg_normal_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/common_google_signin_btn_text_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_low_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_low_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-mdpi-v4/notification_bg_normal_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_low_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_low_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_normal.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xhdpi-v4/notification_bg_normal_pressed.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/common_google_signin_btn_icon_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/common_google_signin_btn_icon_light_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/common_google_signin_btn_text_dark_normal_background.9.png.
DBG [Yaml] Removed item from doNotCompress: res/drawable-xxhdpi-v4/common_google_signin_btn_text_light_normal_background.9.png.
DBG [Res][Begin] Merging app resources.
DBG [Res][Begin] Merging app resources of type Animator.
DBG [Res][End] Merging app resources of type Animator
DBG [Res][Begin] Merging app resources of type Anim.
DBG [Res][End] Merging app resources of type Anim
DBG [Res][Begin] Merging app resources of type Color.
DBG [Res][End] Merging app resources of type Color
DBG [Res][Begin] Merging app resources of type Drawable.
DBG [Res][End] Merging app resources of type Drawable
DBG [Res][Begin] Merging app resources of type MipMap.
DBG [Res][End] Merging app resources of type MipMap
DBG [Res][Begin] Merging app resources of type Layout.
DBG [Res][End] Merging app resources of type Layout
DBG [Res][Begin] Merging app resources of type Menu.
DBG [Res][End] Merging app resources of type Menu
DBG [Res][Begin] Merging app resources of type Raw.
DBG [Res][End] Merging app resources of type Raw
DBG [Res][Begin] Merging app resources of type Values.
DBG [Res][End] Merging app resources of type Values
DBG [Res][Begin] Merging app resources of type Xml.
DBG [Res][End] Merging app resources of type Xml
INF Checking whether resources has changed...
INF Building resources...
DBG [Res][End] Merging app resources.
DBG [WrapperAgent][End] Updating app resources.
ERR Failed to package app.
	com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:147)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
	brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\MFekry\AppData\Local\Temp\brut_util_Jar_2140765927257332877.tmp, compile, --dir, C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\sourceApk\res, --legacy, -o, C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\sourceApk\build\resources.zip]
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:503)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:142)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
	brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\MFekry\AppData\Local\Temp\brut_util_Jar_2140765927257332877.tmp, compile, --dir, C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\sourceApk\res, --legacy, -o, C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\sourceApk\build\resources.zip]
		brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:362)
		brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:601)
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:142)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
	brut.common.BrutException: could not exec (exit code = -1073741515): [C:\Users\MFekry\AppData\Local\Temp\brut_util_Jar_2140765927257332877.tmp, compile, --dir, C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\sourceApk\res, --legacy, -o, C:\Users\MFekry\AppData\Local\Temp\IntuneAppWrappingTool-4156203532247506112\sourceApk\build\resources.zip]
		brut.util.OS.exec(OS.java:98)
		brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:358)
		brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:601)
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:481)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:142)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:97)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:145)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:220)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:58)
ERR Failed to load app resource table.

**Comment by rygo-msft** [comment]
This is as known issue. For workaround details, please see https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/issues/27

**Comment by mfekry** [comment]
thx it was java issue as mentioned at your link
