### ISSUE TITLE
Getting error on building apk

### ISSUE THREAD

**Issue by donny08** [msintuneappsdk/intune-app-wrapping-tool-android#31]
**Describe the bug:**
Application wrapping in progress. App Wrapping Tool Version: 1.0.2554.2
[main manifest:5] Manifest has more than one /manifest/uses-permission[@name=android.permission.INTERNET] element.
C:\Users\CHARLE~1\AppData\Local\Temp\IntuneAppWrappingTool-2941818379944089507\sourceApk\res\values\public.xml:1104: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
C:\Users\CHARLE~1\AppData\Local\Temp\IntuneAppWrappingTool-2941818379944089507\sourceApk\res\values\public.xml:1105: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1'. Invalid character '$avd_hide_password__1'.
C:\Users\CHARLE~1\AppData\Local\Temp\IntuneAppWrappingTool-2941818379944089507\sourceApk\res\values\public.xml:1106: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2'. Invalid character '$avd_hide_password__2'.
C:\Users\CHARLE~1\AppData\Local\Temp\IntuneAppWrappingTool-2941818379944089507\sourceApk\res\values\public.xml:1107: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0'. Invalid character '$avd_show_password__0'.
C:\Users\CHARLE~1\AppData\Local\Temp\IntuneAppWrappingTool-2941818379944089507\sourceApk\res\values\public.xml:1108: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1'. Invalid character '$avd_show_password__1'.
C:\Users\CHARLE~1\AppData\Local\Temp\IntuneAppWrappingTool-2941818379944089507\sourceApk\res\values\public.xml:1109: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2'. Invalid character '$avd_show_password__2'.

**Comment by donny08** [comment]
@rygo-msft Any help with this

**Comment by rygo-msft** [comment]
Hi @donny08, can you please attach the full log file.
There should be a message at the end of wrapping that describes the log file location. It should look like `Verbose logs can be found at: <filepath>`

**Comment by rygo-msft** [comment]
Closing this issue because we need more information. If you can provide the verbose log file, we can reopen the issue.
