### ISSUE TITLE
Wrapped application cannot run.

### ISSUE THREAD

**Issue by shaoxd9** [msintuneappsdk/intune-app-wrapping-tool-android#35]
**Describe the bug:**
When run wrapped application popup error dialog which says that "This app must be managed by Microsoft Intune, but your account has not been set up. Contact your IT administrator for help".  

**To Reproduce**
1. use tool wrap the application
2. update it as a LOB in Device Manager.
3. Android download and install it by Company portal.
4. Open application and input password.

**Expected behavior:**
Should work

**Screenshots and logs:**

![error-not-set](https://user-images.githubusercontent.com/50045667/76697248-e08fb800-66cf-11ea-976d-592f817d7a35.png)

**Comment by meghandaly** [comment]
@shaoxd9 You need to ensure that the user's account has an Intune license assigned in the Microsoft 365 admin center. Please see [Error messages and dialogs on Android](https://docs.microsoft.com/en-us/troubleshoot/mem/intune/troubleshoot-mam#error-messages-and-dialogs-on-android) for more information on troubleshooting these types of messages.
