### ISSUE TITLE
Wrapping fails when using aar and not matching the minSdkVersion

### ISSUE THREAD

**Issue by vauvenal5** [msintuneappsdk/intune-app-wrapping-tool-android#37]
When wrapping an app that uses an aar library the wrapping process fails. The used aar library has a minSdkVersion of 21 and the app has a minSdkVersion of 26. However when the app is set to have the same minSdkVersion as the aar library the wrapping succeeds.

I expected the wrapping to work since Android does not require app and aar to have matching minSdkVersions as long as the version of the app is equal or higher.

I am not able to provide any code for reproduction, however, I am appending a log file of the failing wrapping run and a log file of the successful wrapping run.

Log of failed run:
[IntuneAppWrappingToolLog_20200518_111702-min26.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/4643371/IntuneAppWrappingToolLog_20200518_111702-min26.txt)

Log of successfull run:
[IntuneAppWrappingToolLog_20200518_113626-min21.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/4643374/IntuneAppWrappingToolLog_20200518_113626-min21.txt)

Additional Information:
- targetSdk: 29
- compileSdk: 29
- intune app wrapping tool version: 1.0.2896.3

**Comment by meghandaly** [comment]
@vauvenal5 We have a fix for this issue and it will be available in our upcoming release targeting early 2021.

**Comment by vauvenal5** [comment]
Thanks for the update. Sadly I won't be able to verify it myself, since I am no longer working on that project.

**Comment by meghandaly** [comment]
This issue is resolved in the latest release [1.0.3199.5](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/tag/1.0.3199.5).
