### ISSUE TITLE
The hyperlink to  Protect line-of-business apps and data on devices not enrolled in Microsoft Intune is broken

### ISSUE THREAD

**Issue by shawnwangms** [msintuneappsdk/intune-app-wrapping-tool-android#39]
**Describe the bug:**
As subject. Please fix it. Thanks.

**To Reproduce**
1. Go to 'https://docs.microsoft.com/en-us/intune/deploy-use/protect-line-of-business-apps-and-data-on-devices-not-enrolled-in-microsoft-intune'
2. See error - "404-Page not found"

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is crashing post-wrapping, do you have app logs for the crash itself? 
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors? 

**Smartphone (please complete the following information):**

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by meghandaly** [comment]
@shawnwangms Thank you for reporting the broken link. It has been corrected.
