### ISSUE TITLE
App Installation fails from play store in Work profile

### ISSUE THREAD

**Issue by prashant-nigam** [msintuneappsdk/intune-app-wrapping-tool-android#40]
I am adding a fix for Android 10 to add '**requestLegacyExternalStorage**' tag for which I have to use the v1.0.2963.3 of intune wrapping tool. But after wrapping the application and publishing on play store. The app fails to install with message 

The debug and release versions of the android app with Android 10 fix installs properly outside play store. 
When trying to removing the android 10 specific fix and wrapping with v1.0.2676.4 version of Intune wrapping tool and publishing on play store, the app installs successfully and works properly.

**Comment by rygo-msft** [comment]
@prashant-nigam, can you please provide more information on the issue your are seeing? What is the failure message? Does the installation failure occur if you wrap the known good version of the app with the latest app wrapper, or only when adding the requestLegacyExternalStorage flag?

**Comment by prashant-nigam** [comment]
@rygo-msft, message is "Can't install app". Failure occur when wrapping the good version of the app with latest wrapper.
![Screenshot_20200901-064508_Google Play Store](https://user-images.githubusercontent.com/34888590/91783946-3b39b380-ec1f-11ea-8c1d-568adb9baf75.jpg)

**Comment by prashant-nigam** [comment]
This issue is fixed
