### ISSUE TITLE
 Wrapping apps targeting API 30 not yet supported

### ISSUE THREAD

**Issue by dongsikkim** [msintuneappsdk/intune-app-wrapping-tool-android#41]
com.microsoft.intune.mam.apppackager.utils.AppPackagerException: This app's target API level is above the MAM target API level. App target: 30, MAM target: 29. Please upgrade to the newest version of the App Wrapping Tool if available.

I am currently using version 1.0.2963.3.
Is there a newer version than this one?
Or is there a way to solve the above issue?

**Comment by rygo-msft** [comment]
Hello, this is expected as the App Wrapper does not yet support wrapping apps that target API 30. Support will be added in a future release.

**Comment by meghandaly** [comment]
Support for targeting API 30 is included in the latest release [1.0.3199.5](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/tag/1.0.3199.5).
