### ISSUE TITLE
App Wrapping Failed - Using latest Wrapping Tool

### ISSUE THREAD

**Issue by prateekrewardz** [msintuneappsdk/intune-app-wrapping-tool-android#42]
Environment Used: Windows 10 - 64 Bit, Java 64 Bit Latest Version
INtune version : 1.0.2963.3

TRYING TO wrap an Android app, but facing below issue:

VRB X509Certificate: Alg:{0}, Serial:{1}, Subject:{2}, Issuer:{3}, Key type:{4}, Length:{5}, Cert Id:{6}, Valid from:{7}, Valid until:{8}
WRN Application wrapping in progress. App Wrapping Tool Version: 1.0.2963.3
DBG [Diagnostic][BEGIN] Runtime information.
DBG [Diagnostic] OS Version: Windows 10
DBG [Diagnostic] Java version: 1.8
DBG [Diagnostic] JVM Bitness: amd64
DBG [Diagnostic][END] Runtime information.
DBG Begin Packaging: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\.\SAHATAK-v1.apk
DBG [APKTool] Begin decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\.\SAHATAK-v1.apk
INF Using Apktool 2.4.1 on SAHATAK-v1.apk
INF Loading resource table...
INF Decoding AndroidManifest.xml with resources...
INF Loading resource table from file: C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\framework\1.apk
INF Regular manifest package...
INF Decoding file-resources...
VRB Win version: 0x3ad7000a = 987168778 (Windows Vista)
INF Decoding values */* XMLs...
INF Baksmaling classes.dex...
INF Baksmaling classes2.dex...
INF Copying assets and libs...
INF Copying unknown files...
INF Copying original files...
DBG [APKTool] Finish decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\.\SAHATAK-v1.apk
DBG [APKTool] Begin decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\lib\IntuneAppBase.apk
INF Using Apktool 2.4.1 on IntuneAppBase.apk
INF Loading resource table...
INF Decoding AndroidManifest.xml with resources...
INF Loading resource table from file: C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\framework\1.apk
INF Regular manifest package...
INF Decoding file-resources...
INF Decoding values */* XMLs...
INF Baksmaling classes.dex...
INF Copying assets and libs...
INF Copying unknown files...
INF Copying original files...
DBG [APKTool] Finish decoding APK file: C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\lib\IntuneAppBase.apk
DBG [Diagnostic][Begin] App build tool information.
DBG [Diagnostic] CompileSdkVersion: 29
DBG [Diagnostic] PlatformBuildVersion: 29
DBG [Diagnostic][End] App build tool information.
DBG [Diagnostic][Begin] App dependency information.
DBG [Diagnostic][End] App dependency information.
DBG [WrapperAgent][Begin] Updating app manifest.
DBG [Manifest] Begin merging manifests.
DBG [Manifest] Finish merging manifests.
INF [Yaml] Input app's minimum API level was raised to MAM minimum API level: 19
INF [Yaml] Updating API level for minSdkVersion to 19.
DBG [WrapperAgent][End] Updating app manifest.
DBG [WrapperAgent][Begin] Updating app resources.
DBG [Res][Begin] Merging app resources.
DBG [Res][Begin] Merging app resources of type Animator.
DBG [Res][End] Merging app resources of type Animator
DBG [Res][Begin] Merging app resources of type Anim.
DBG [Res][End] Merging app resources of type Anim
DBG [Res][Begin] Merging app resources of type Color.
DBG [Res][End] Merging app resources of type Color
DBG [Res][Begin] Merging app resources of type Drawable.
DBG [Res][End] Merging app resources of type Drawable
DBG [Res][Begin] Merging app resources of type MipMap.
DBG [Res][End] Merging app resources of type MipMap
DBG [Res][Begin] Merging app resources of type Layout.
DBG [Res][End] Merging app resources of type Layout
DBG [Res][Begin] Merging app resources of type Menu.
DBG [Res][End] Merging app resources of type Menu
DBG [Res][Begin] Merging app resources of type Raw.
DBG [Res][End] Merging app resources of type Raw
DBG [Res][Begin] Merging app resources of type Values.
DBG [Res][End] Merging app resources of type Values
DBG [Res][Begin] Merging app resources of type Xml.
DBG [Res][End] Merging app resources of type Xml
INF Checking whether resources has changed...
INF Building resources...
DBG Merging Resources Failed.
DBG [Res][End] Merging app resources.
DBG [WrapperAgent][End] Updating app resources.
ERR Failed to package app.
	com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to load app resource table.
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:159)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:102)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:177)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
	brut.androlib.AndrolibException: brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Rajendra\AppData\Local\Temp\brut_util_Jar_4702953810415009228.tmp, compile, --dir, C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res, --legacy, -o, C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\build\resources.zip]
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:502)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:150)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:102)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:177)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
	brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Rajendra\AppData\Local\Temp\brut_util_Jar_4702953810415009228.tmp, compile, --dir, C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res, --legacy, -o, C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\build\resources.zip]
		brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:385)
		brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:637)
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:480)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:150)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:102)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:177)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
	brut.common.BrutException: could not exec (exit code = 1): [C:\Users\Rajendra\AppData\Local\Temp\brut_util_Jar_4702953810415009228.tmp, compile, --dir, C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res, --legacy, -o, C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\build\resources.zip]
		brut.util.OS.exec(OS.java:98)
		brut.androlib.res.AndrolibResources.aapt2Package(AndrolibResources.java:381)
		brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:637)
		brut.androlib.Androlib.buildResourcesFull(Androlib.java:480)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.loadResourceTable(ResourceUtils.java:150)
		com.microsoft.intune.mam.apppackager.utils.ResourceUtils.mergeResources(ResourceUtils.java:102)
		com.microsoft.intune.mam.apppackager.WrapperAgent.wrapResources(WrapperAgent.java:177)
		com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:66)
		com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
		com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
		com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\plurals.xml:39: error: invalid value for type 'plurals'. Expected a reference.
ERR Failed to load app resource table.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\plurals.xml: error: file failed to compile.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\public.xml:2209: error: resource 'drawable/$avd_hide_password__0' has invalid entry name '$avd_hide_password__0'. Invalid character '$avd_hide_password__0'.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\public.xml:2210: error: resource 'drawable/$avd_hide_password__1' has invalid entry name '$avd_hide_password__1'. Invalid character '$avd_hide_password__1'.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\public.xml:2211: error: resource 'drawable/$avd_hide_password__2' has invalid entry name '$avd_hide_password__2'. Invalid character '$avd_hide_password__2'.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\public.xml:2212: error: resource 'drawable/$avd_show_password__0' has invalid entry name '$avd_show_password__0'. Invalid character '$avd_show_password__0'.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\public.xml:2213: error: resource 'drawable/$avd_show_password__1' has invalid entry name '$avd_show_password__1'. Invalid character '$avd_show_password__1'.
WRN C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingTool-5455595280992430625\sourceApk\res\values\public.xml:2214: error: resource 'drawable/$avd_show_password__2' has invalid entry name '$avd_show_password__2'. Invalid character '$avd_show_password__2'.
WRN Verbose logs can be found at: C:\Users\Rajendra\AppData\Local\Temp\IntuneAppWrappingToolLog_20201022_201939.txt.
ERR The application could not be wrapped.

Can someone please help to resolve this.

**Comment by prateekrewardz** [comment]
Can i get some response here? Please

**Comment by meghandaly** [comment]
@prateekrewardz Apologies for the delay. Do you have a test APK that you are willing to share the repros the issue?

**Comment by prateekrewardz** [comment]
Yes, I can share a test apk. But won't be able to share a keystore file and password. Is it possible to get on a zoom meeting and do a screen sharing session?

**Comment by meghandaly** [comment]
@prateekrewardz Thank you for the prompt reply. That's okay, I don't need that information. The APK will greatly help for the time being.

**Comment by prateekrewardz** [comment]
https://drive.google.com/file/d/1iMQ3fs9DCFkDV6KlsRqzSLt_eGpG7BE1/view?usp=sharing

Here you go. If you are not able to download then please share your email id

**Comment by meghandaly** [comment]
I am not able to download, but we have a repro in house with a test APK. I am marking this as a bug and working on a fix.

**Comment by prateekrewardz** [comment]
Thank you Meghan. Just in case you need to download, you can use this public link
https://www.dropbox.com/s/11s4mhhd8ifgf1k/app-SAHATAK-release%20Nov%203.apk?dl=0

also, May I know when can I have a resolution for this?

**Comment by meghandaly** [comment]
@prateekrewardz We have a fix for this issue and it will be available in our upcoming release targeting early 2021.

**Comment by prateekrewardz** [comment]
Hi @meghandaly , Wish you a very happy new year. May I know if we have some dates to release this fix? It's holding two of my customer releases. 
Thank you

**Comment by meghandaly** [comment]
@prateekrewardz We are in the process of finalizing our release and hope to ship the fix within the next couple of weeks.

**Comment by meghandaly** [comment]
Hi @prateekrewardz, this issue is resolved in the latest release [1.0.3199.5](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/tag/1.0.3199.5).
