### ISSUE TITLE
Failed to Wrap App - error: unexpected element <queries> found in <manifest>

### ISSUE THREAD

**Issue by Prabhakaran-Ganesan** [msintuneappsdk/intune-app-wrapping-tool-android#43]
**Description**
We have built an Android app that integrates with Microsoft identity platform which contains the dependency of  the library ‘com.microsoft.identity.client:msal:2.0.4'. 

The app is working well with normal installation in an android phone.
But while trying to wrap the app, following error occurred.

![image](https://user-images.githubusercontent.com/76149299/105842218-dc287100-5ffb-11eb-979a-a11662329f77.png)

**To Reproduce**
1. Create a blank project in android studio
2. Add the MSAL dependency ( ‘com.microsoft.identity.client:msal:2.0.4' )
3. Build the project
4. Try wrapping the release output apk.
5. The above mentioned error occurred.

**Details**
Appwrapping tool version - 1.0.2963.3
Android Studio - 4.1.1
App targetSdkVersion - 29

**Logs:**

Complete log can be found in the attachment
[IntuneAppWrappingToolLog_20201215_100644.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/5873241/IntuneAppWrappingToolLog_20201215_100644.txt)

**Intune app wrapping tool :**
- What version of the wrapper are you using?
- 1.0.2963.3
-  Are you using the latest version?
- Yes
- For pre-wrapping errors, does the app build without being wrapped?
- Yes, the build was successful without wrapping
- For post-wrapping errors, does the app launch without being wrapped?
- Yes, the app is launching without being wrapped

**Additional context:**
When I use the older version of MSAL dependency (1.6.+), the app is wrapping successfully without this error.

@msintuneappsdk For traceability, mentioning the microsoft intune support ticket number 23299940

**Comment by meghandaly** [comment]
@Prabhakaran-Ganesan we believe this issue is resolved in our latest release, [1.0.3199.5](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/tag/1.0.3199.5).

Can you please try with that version and let us know if you still encounter the issue?

**Comment by Prabhakaran-Ganesan** [comment]
@meghandaly  Our app has been wrapped successfully with the latest version (1.0.3199.5.)
Thank you so much for the support.
