### ISSUE TITLE
Unable to use LinkedIn learning, it is always showing this error. I tried login via my mail as well as my official mail id but nothing works. How i can register my mobile device in my company Portal

### ISSUE THREAD

**Issue by yamuna7892** [msintuneappsdk/intune-app-wrapping-tool-android#47]
Request Id: 2a1f59e9-913c-4db0-a6ee-41caa2742f01
Correlation Id: 80f625e3-0854-4c11-a1ed-d084000df647
Timestamp: 2021-05-22T22:10:29Z
Message: AADSTS90014: The required field 'request' is missing from the credential. Ensure that you have all the necessary parameters for the login request.

**Comment by meghandaly** [comment]
@yamuna7892 This channel is not monitored by support and is intended for help wrapping Android APKs for use with Intune.
