### ISSUE TITLE
Brokered authentication does not work with target/compile SDK set to 30

### ISSUE THREAD

**Issue by ryandegruyter** [msintuneappsdk/intune-app-wrapping-tool-android#49]
**Describe the bug:**

Brokered authentication with Microsoft Company portal works with:
- minSdkVersion = 21
- compileSdkVersion = 29
- targetSdkVersion = 29

But when I change it to
- minSdkVersion = 21
- compileSdkVersion = 30
- targetSdkVersion = 30

Instead, a Microsoft login page is opened and device management state can't be retrieved during auth.
 
**To Reproduce**
See above

**Expected behavior:**
Brokered authentication still works.

**Screenshots and logs:**
Before (SDK 29):
<img src="https://user-images.githubusercontent.com/12190633/123714606-f26e7d80-d876-11eb-8aa9-010e309847c0.png" width=300 />

After (SDK 30):
<img src=https://user-images.githubusercontent.com/12190633/123714618-f9958b80-d876-11eb-9eef-a8262f423bbb.png width=300 />

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 11

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
Latest version

- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Capacitor and Cordova

- For pre-wrapping errors, does the app build without being wrapped?
yes

- For post-wrapping errors, does the app launch without being wrapped?
yes

- Do you see a trend with it only being reproduced on a specific device?
all Androids

**Comment by rygo-msft** [comment]
Hi @ryandegruyter,
The App Wrapping Tool doesn't make any changes to app authentication, so I wouldn't expect it to cause any issues. Are you using ADAL or MSAL for authentication? Auth logs would help to diagnose the issue.

**Comment by ryandegruyter** [comment]
hi @rygo-msft, it might have been a misconfig from our side. We moved away from the wrapper and started integrating the SDK which gives us better results.
