### ISSUE TITLE
Wrapping failed for android 

### ISSUE THREAD

**Issue by Abhijith-G** [msintuneappsdk/intune-app-wrapping-tool-android#5]
Hi Team,
I am using  App Wrapping Tool Version: 1.0.1659.2, Hope this is the lattest one. But i got error messages like this . PFB errors. Please help me. Thanks 
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to update this app's supported SDK versions.
                com.microsoft.intune.mam.apppackager.utils.YamlManifestUtils.updateAppSupportedSdkRange(YamlManifestUtils.java:324)
                com.microsoft.intune.mam.apppackager.v2.V2WrapperAgent.wrapManifest(V2WrapperAgent.java:86)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:69)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:132)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:198)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:56)
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: This app's target SDK is above the MAM target SDK. Please upgrade to the newest version of the App Wrappin
g Tool.
                com.microsoft.intune.mam.apppackager.utils.YamlManifestUtils.updateAppSupportedSdkRange(YamlManifestUtils.java:305)
                com.microsoft.intune.mam.apppackager.v2.V2WrapperAgent.wrapManifest(V2WrapperAgent.java:86)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:69)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:132)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:198)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:56)
The application could not be wrapped...

**Comment by msintuneappsdk** [comment]
Hi Abhijith - What are the max and min values set on your app with respect to the Android API levels?

**Comment by Abhijith-G** [comment]
Minimum api level is 18 and maximum api level is 24, please help on this, thanks

**Comment by Abhijith-G** [comment]
Any update on this

**Comment by Jitender-Yadav** [comment]
Hi Team, I am facing the exact same issue.
Please help solving this.

**Comment by msintuneappsdk** [comment]
@Abhijith-G Please confirm that the app's maximum API level is set to 24 and let us know if you are still experiencing the error.

@Jitender-Yadav What are the max and min values set on your app with respect to the Android API levels?

**Comment by Jitender-Yadav** [comment]
minimum API level set is - 18
maximum API level set is - 24

Thanks for your reply.

**Comment by Jitender-Yadav** [comment]
@Abhijith-G  If You are still facing the problem, I found a solution to it, see if this helps. Assuming you have already tried setting minsdkversion and maxsdkversion to 18 and 24 in Android Manifest file and are still facing this issue. 
If you are using Android studio, go to the Gradle Scripts and open the build.gradle file, make sure in the build.gradle file the compilesdkversion and targetsdkversion are <= 24. If they are not (as in my case) , I installed a previous version of Android Studio (version 1.5) and everything worked smoothly.
Hope this helps..!

**Comment by msintuneappsdk** [comment]
Hi @Abhijith-G are you still experiencing issues with the latest issue of the Intune AWT for Android? Please let us know.

**Comment by Abhijith-G** [comment]
Hi I have experienced new error while wrapping xamarin based app in both android and IOS.
In IOS,
After wrapping and  we have deployed into our intune store. Then we installed app from our store. After launching the app, it asked Microsoft login. After success full login to Microsoft id(company Id), the app has gone to one page and shows a pop up with app not set up for you and contact administrator error. Please check on this

In android
After downloading app from store, the app stuck on launch 
Could you please help  on this issue

**Comment by cocowalla** [comment]
I have the same issue - given it's been open since May, it would be nice if someone from Microsoft could look at it!

I have `android-targetSdkVersion` set to `24` in my `config.xml`. However, after the failed build attempt, I can see a file `platforms\android\build\intermediates\manifests\full\debug\AndroidManifest.xml` which contains `android:targetSdkVersion="25"` - this file also contains `net.hockeyapp.android`... the app in question does indeed use HockeyApp as well as the Intune SDK, so my guess is that there is a conflict here - HockeyApp appears to target Android SDK 25, whereas the Intune SDK (still!) doesn't support 25.

Anyone else in this thread also using HockeyApp?

**Comment by sjkp** [comment]
@msintuneappsdk what is the ETA for fix on this? Have clients waiting for it.

**Comment by michaelreiser** [comment]
Also looking for an update.  Thx
