### ISSUE TITLE
Android Wrapper + MSAL

### ISSUE THREAD

**Issue by rrmiraz** [msintuneappsdk/intune-app-wrapping-tool-android#50]
Hi,

I’m using Intune Wrapper + MSAL library to log into an app with Conditional Access enabled that only allows Microsoft trusted apps or apps protected by intune.

The problem is that CA is not detecting that our app is protected by intune since intune login and MSAL login are completely separated.

Is this the expected behaviour? Or CA with intune wrapper + MSAL should work?

**Comment by rygo-msft** [comment]
Hi @rrmiraz,

Can you provide more information about your issue? Which CA policy are you trying to configure? Can you reproduce the issue and then share the Id for the logs from the Company Portal by following the steps here: https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android

**Comment by lokibyte** [comment]
Hi Can we get Mac OS compatible Intune App Wrapping Tool for android ?

**Comment by codylund** [comment]
Closing as stale because we have not received additional information within the last 30 days.

**Comment by codylund** [comment]
@lokibyte we currently are not planning to support the Intune App Wrapping Tool on Mac OS. However, I can open an internal task to track the feature request on our side.
