### ISSUE TITLE
API level 31 targeting

### ISSUE THREAD

**Issue by lsimmm** [msintuneappsdk/intune-app-wrapping-tool-android#54]
Just want to wrap an app with level 31 target, but cant as the current version only supports up to API 30.

Do you know when this version of the tool will be available?

**************************************************************************************************

Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: This app's target API level is above the MAM target API level. App target: 31, MAM target: 30. Please upgrade to the newest version of the App Wrapping Tool if available.
                com.microsoft.intune.mam.apppackager.utils.YamlManifestUtils.validateAppSupportedSdkRange(YamlManifestUtils.java:317)
                com.microsoft.intune.mam.apppackager.WrapperAgent.validateTargetApp(WrapperAgent.java:71)
                com.microsoft.intune.mam.apppackager.AbstractWrapperAgent.wrap(AbstractWrapperAgent.java:64)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:117)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
This app's target API level is above the MAM target API level. App target: 31, MAM target: 30. Please upgrade to the newest version of the App Wrapping Tool if available.

**Comment by meghandaly** [comment]
Hi @lsimmm , we are looking to release an updated version with API 31 support in the first half of this calendar year, 2022. When we have a more specific release timeline we will share it here.

**Comment by codylund** [comment]
This is supported in the latest release, version 1.0.3610.6.
