### ISSUE TITLE
The application could not be wrapped

### ISSUE THREAD

**Issue by paul590** [msintuneappsdk/intune-app-wrapping-tool-android#6]
Hi Team,

I am currently trying to wrap an apk with the latest wrapping tool. However, I keep getting the error found below. Please note I have made sure my minSDKversion is 18 and targetSdkVersion is 21, I have also made sure of this on my Android Manifest. I have also experienced issues before with files in my res folder that end with for example filename.9.xml. I have also removed these files from my application as well. Weirdly this error only happens with a few apk but the others wrap with no problems. Any ideas would be great! The error that I am receiving is the following:

The application could not be wrapped.
        java.lang.NullPointerException
                brut.androlib.res.data.value.ResStyleValue.serializeToResValuesXml(ResStyleVa
                brut.androlib.res.AndrolibResources.generateValuesFile(AndrolibResources.java
                brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:267)
                brut.androlib.Androlib.decodeResourcesFull(Androlib.java:132)
                brut.androlib.ApkDecoder.decode(ApkDecoder.java:108)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.decodeAPK(APKToolWr
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.j
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:56)

Thank you for your help!

**Comment by msintuneappsdk** [comment]
Hi Paul - thanks for reaching out. We have some follow-up questions. Please send an email to 
msintuneappsdk@microsoft.com and we can get started debugging your issue.

**Comment by juud3x** [comment]
Hey, having the exact same issue. If a resolution was found any help would be appreciated

**Comment by msintuneappsdk** [comment]
Hi @juud3x. Please send an email to msintuneappsdk@microsoft.com as we would need some more information from you to debug.
