### ISSUE TITLE
App Upload Issue "Signature Invalid or does not exists"

### ISSUE THREAD

**Issue by vishal-shukla-viitorcloud** [msintuneappsdk/intune-app-wrapping-tool-android#63]
**Issue:** 

Our Client using Managed Google play console where he upload signed APK which is wrapped with intune. 

So when uploading app first time, they are getting issue "Signature invalid or does not exist"

**Steps to generate & wrap app:**

1. Generate Signed apk from android studio

2. Generate unsigned apk from intune wrap
    - Invoke-AppWrappingTool -InputPath ".apk" -OutputPath "outfolder*.apk" -KeyStorePath ".jks" -KeyAlias **

3. Sign APK
   - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -storepass ** -keystore *\unsigned.apk alias

4. Verify APK 
  - zipalign -v 4 *\unsigned.apk   *\app-intune.apk

These 4 steps worked successfully.

**Query/Note:**
This app is being uploaded first time so is there any problem with signing key? 

their account managing many apps. so it may happen that they have their own signgkey map with account and used for all apps being uploaded? 

OR it will take current keystore details from signed apk? 

Help me asap. Thanks.

![image](https://user-images.githubusercontent.com/77824464/164615860-c47def27-d754-4035-916f-ef5f73189511.png)

**Comment by vishal-shukla-viitorcloud** [comment]
Anyone can help?

**Comment by rygo-msft** [comment]
@vishal-shukla-viitorcloud if you do not wish to sign you apk, you should not provide any of the keystore parameters to the wrapping tool. Signing using the App Wrapping Tool is deprecated and you should leverage the Android SDK signing tools instead.

https://developer.android.com/studio/publish/app-signing
https://developer.android.com/studio/command-line/apksigner

We are unable to provide support here for tools other than the App Wrapping Tool itself. If you would like assistance with publishing, you can contact MEM support https://docs.microsoft.com/en-us/mem/get-support
