### ISSUE TITLE
[Feature Request] App Wrapper Support For API 32 and 33 Targeting

### ISSUE THREAD

**Issue by meghandaly** [msintuneappsdk/intune-app-wrapping-tool-android#64]
### Feature Request

Increase targeting support from API 31 to API 32.

### Reason for Request

Support for the latest APIs.

### Preferred Solution

A new App Wrapper release with API 32 targeting support.

## Questions to Ask Before Submission

1. Has the feature you are requesting already been submitted?
2. Are you using the latest App Wrapper version?

Opened in response to the request in #60

**Comment by meghandaly** [comment]
@sagar-sg  The delta between API 31 and API 32 is small and was mostly designed for large format devices. Do you explicitly require the API surface added in API 32?

**Comment by sagar-sg** [comment]
@meghandaly Our app APK is targeting the api version 32 , hence we require it accordingly. Intune SDK is throwing error For API 31, We cannot change it back to 31 every time for wrapping with intune sdk. So we require solution for this.

**Comment by xzetic05** [comment]
@meghandaly Hi, we are one of the application team that waiting for this feature update. May i know if you already have some update or time when this feature will be release? Thank you!

**Comment by rygo-msft** [comment]
We require support from APKTool in order to add support for wrapping API 32 and API 33. Per the APKTool item https://github.com/iBotPeaches/Apktool/issues/2938, APKTool support is not expected until the end of this year. Intune will not be able to provide support for targeting API 32 or 33 until then.

**Comment by xzetic05** [comment]
@rygo-msft thanks for your input, I have seen the APKTool item that support for API 32 and API 33 will be included on v2.6.2, hope they can release it by end of year so we can plan our upgrade too by next year, Thank you!

**Comment by yaxin3690** [comment]
apktool project has supported api 33 in version 2.7.0. When will your company update this tool? Thanks! Specific reference information is as follows: [](https://connortumbleson.com/2022/11/24/apktool-v2-7-0-released/)

**Comment by yaxin3690** [comment]
apktool project has supported api 33 in version 2.7.0. When will your company update this tool? Thanks! Specific reference information is as follows: https://connortumbleson.com/2022/11/24/apktool-v2-7-0-released/

**Comment by pdarcy97** [comment]
Hi, is there any update on when a new release of the app wrapper can be expected to support this?

**Comment by AhmadTK** [comment]
we are also here stuck with the same issue

**Comment by meghandaly** [comment]
Latest release with API 32 and 33 support is live! [Release 1.0.3935.1](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/tag/1.0.3935.1) 🥳
