### ISSUE TITLE
[Feature Request] Flutter apk intune wrapping tool

### ISSUE THREAD

**Issue by debopriyoo** [msintuneappsdk/intune-app-wrapping-tool-android#66]
Is it possible to wrap a flutter apk, by using android wrapping tool to use it in only android devices? If not how to make a flutter apk intune compatible?

**Comment by it-monkey** [comment]
Any news on this?

**Comment by meghandaly** [comment]
The App Wrapping tool should be compatible with Flutter apps. Are you experiencing issues wrapping a Flutter app? If so, please open a separate bug tickets with additional details.
