### ISSUE TITLE
intune wrapper - android not working

### ISSUE THREAD

**Issue by AbhiAidan** [msintuneappsdk/intune-app-wrapping-tool-android#72]
## Information
Intune android wrapper - not able to wrap. 

## Steps followed
1. Generated signed apk.
2. Installed latest wrapper tool.
3. From the folder -  Import-Module .\IntuneAppWrappingTool.psm1
4. Run - Invoke-AppWrappingTool -InputPath "C:\AWT\AppSource\app-release.apk" -OutputPath "C:\AWT\AppWrapped\output.apk" -verbose

### Details

1. **App Wrapper Version: **1.0.3610.6**:
5. **Operating System (Mac, Linux, Windows) and Version**: **Windows**
6. **Java Version**: **17.0.5**
7. **Development Platform (Java, Xamarin, Cordova, React)**: **Ionic**
8. **`build-tools` Version**:

### Stack Trace for Building the App Resource Table
![image](https://user-images.githubusercontent.com/111577219/198215081-f8d9744d-3f4c-4d22-8de6-0f7792ad757b.png)

## Questions to Ask Before Submission

1. Does the app build and launch without being wrapped? **Yes**
2. Have you checked the [Apktool repository](https://github.com/iBotPeaches/Apktool) for similar issues? If so, please follow the guidance there or add that information to this issue. 
3. Are you using the latest App Wrapper version? **Yes**

**Comment by rygo-msft** [comment]
@AbhiAidan, App Wrapper does not support Java 17. We rely on the Android build toolchain which is only known to work on Java 11. Please ensure that you are running the App Wrapper with Java 11.

**Comment by AbhiAidan** [comment]
@rygo-msft Thanks. Appreciate your help. Did you able to found any other things i'm doing wrong, other than this.

**Comment by rygo-msft** [comment]
Unfortunately, I can't read the image that you shared because it is too compressed. However, there are known failures that will occur when running on unsupported versions of Java.
