### ISSUE TITLE
[Feature Request] [TODO]

### ISSUE THREAD

**Issue by yaxin3690** [msintuneappsdk/intune-app-wrapping-tool-android#74]
**Describe the bug:**
com.microsoft.intune.mam.client.fileencryption.MAMKeyAccessNotAllowedException: Encryption keys only available to managed apps
14:27:25.193 30356-30493 System.err                      W  	at com.microsoft.intune.mam.client.fileencryption.FileEncryptionKeyCacheImpl.retrieveKey(:136)
14:27:25.193 30356-30493 System.err                      W  	at com.microsoft.intune.mam.client.ipcclient.HmacManagerImpl.hmac(:63)
14:27:25.193 30356-30493 System.err                      W  	at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.hmac(:855)
14:27:25.193 30356-30493 System.err                      W  	at libcore.io.Linux.stat(Native Method)
14:27:25.193 30356-30493 System.err                      W  	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
14:27:25.193 30356-30493 System.err                      W  	at android.system.Os.stat(Os.java:565)
14:27:25.193 30356-30493 System.err                      W  	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:147)
14:27:25.193 30356-30493 System.err                      W  	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54)
14:27:25.193 30356-30493 System.err                      W  	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:122)
14:27:25.194   477-477   HisiKeyMaster                   I  out_params_buffer_len = 4096
14:27:25.194   477-477   HisiKeyMaster                   I  hisi_km_begin success
14:27:25.195   477-477   HisiKeyMaster                   I  Disable the enhanced crypto!
14:27:25.195   477-477   teec_app_load                   E  realpath open file erro(No such file or directory), path=/vendor/bin/07070707-0707-0707-0707-070707070707.sec
14:27:25.195 30356-30494 Native                          W  Java exception occurred in JNI call for FileEncryptionManager.hmac. Exception: Encryption keys only available to managed apps
                                                            com.microsoft.intune.mam.client.fileencryption.MAMKeyAccessNotAllowedException: Encryption keys only available to managed apps
                                                            	at com.microsoft.intune.mam.client.fileencryption.FileEncryptionKeyCacheImpl.retrieveKey(:136)
                                                            	at com.microsoft.intune.mam.client.ipcclient.HmacManagerImpl.hmac(:63)
                                                            	at com.microsoft.intune.mam.client.fileencryption.FileEncryptionManager.hmac(:855)
                                                            	at libcore.io.Linux.stat(Native Method)
                                                            	at libcore.io.BlockGuardOs.stat(BlockGuardOs.java:328)
                                                            	at android.system.Os.stat(Os.java:565)
                                                            	at android.app.SharedPreferencesImpl.loadFromDisk(SharedPreferencesImpl.java:147)
                                                            	at android.app.SharedPreferencesImpl.access$000(SharedPreferencesImpl.java:54)
                                                            	at android.app.SharedPreferencesImpl$1.run(SharedPreferencesImpl.java:122)
14:27:25.196 30356-30494 Native                          W  Failed to calculate hmac 0x520230200000051, likely because encryption keys were not available
14:27:25.196 30356-30494 Native                          W  Can't open encrypted private app file because encryption key access isn't allowed
14:27:25.200  4432-4472  PushLog110113300                I  [FileObserver-188]enter cancelAlarm(Action=com.huawei.push.intent.NC_SWITCH_CHANGED
14:27:25.201  1553-1757  AlarmManager                    I  remove alarm:Alarm{34b9cec type 1 when 1669184900233 PendingIntent{b89e8b5: PendingIntentRecord{448320f android broadcastIntent}}android procName null} according to operation:f9d6b4a
**To Reproduce**
1. Use the latest version of AWT tool to integrate intune-sdk into chroium source code (kernel 80.0.0987.99) compiled into apkwe'j without any exception;

2. Register the application on the platform and create policies;

3. Start the application on the mobile phone, pull up the account authentication, and blink back after the authentication is complete;

**Comment by meghandaly** [comment]
@yaxin3690 Please follow the issue template provided for an App Wrapper bug. The current information is not actionable nor fully describes the issue you are encountering.
