### ISSUE TITLE
AppWrapper and `androidx.fragment:fragment` 1.5.0+ Incompatibility

### ISSUE THREAD

**Issue by RamprasathPnr** [msintuneappsdk/intune-app-wrapping-tool-android#75]
**Bug
--------
The Applicaton  is crashing post- Intune wrapping**

1. Install intune wrapped APK
2. Click app from app launcher 
3. The application is crashing when launch itself

**Expected behavior:**
The Application should launch  without crashing

Screenshots and logs:
![intune error](https://user-images.githubusercontent.com/17904191/203712563-19a74472-e006-44aa-9d1c-82f39ff7b3b8.png)

- 

**Smartphones**
 - Device: [Galaxy A7, Galaxy M12]
 - OS: [android 10 ,12]

**Intune app wrapping tool **
- Version of the wrapper -(1.0.3610.6- latest one) 
- Platform is your app based in (Java - android native)
- For post-wrapping errors, Application is wrapped succesfully but app is crashing when launch

**Intune app wrapping tool Steps **

STEP 1
------------------------------------------------------------------------->

Open windows powershell

run following-->
Import-Module "C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\IntuneAppWrappingTool.psm1"

STEP 2
------------------------------------------------------------------------->

invoke-AppWrappingTool -InputPath C:\Users\Admin\Desktop\testApp.apk -OutputPath C:\Users\Admin\Desktop\testApp_wrapped-unsigned.apk -Verbose

STEP 3
------------------------------------------------------------------------->

Go to build-tools path D:\Android\Sdk\build-tools\29.0.3 , 
open cmd    --->

zipalign -v -p 4 "C:\Users\Admin\Desktop\testApp_wrapped-unsigned.apk" "C:\Users\Admin\Desktop\testApp_wrapped-unsigned-aligned.apk"

STEP 4
------------------------------------------------------------------------->

apksigner sign --ks "C:\Users\Admin\Desktop\Keystore.jks" --ks-key-alias abc --out "C:\Users\Admin\Desktop\testApp_wrapped-signed.apk" "C:\Users\Admin\Desktop\testApp_wrapped-unsigned-aligned.apk"

**Comment by mcsimons** [comment]
Thanks for the report, we are aware of this issue. There is an incompatibility between the MAM SDK currently used by AppWrapper and `androidx.lifecycle:lifecycle-runtime` 2.5.0+. (Updating your app to androidx.fragment:fragment 1.5.0+ will include a transitive dependency update from for androidx.lifecycle:lifecycle-* from 2.3.1 to 2.5.0+.) This will be fixed in our next release of AppWrapper which is targeted for the next quarter. Internally tracked by 15017101

**Comment by meghandaly** [comment]
Latest release with API 32 and 33 support is live! [Release 1.0.3935.1](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/tag/1.0.3935.1) 🥳
