### ISSUE TITLE
Package successfully login no response

### ISSUE THREAD

**Issue by 163shuai** [msintuneappsdk/intune-app-wrapping-tool-android#76]
Apps that are distributed through the intune background after intune wrapping are stuck on the login page and do not display errors

    Distribution of the download wrapper Apk via intune backend
    Start the program login account password, and then card master

Expected behavior:
    Can log in

Smartphones
    Device: [GalaxyNode10,HUAWEI YAL-AL00]
    OS: [android 10 ]

Response version
     minSdkVersion 23
     targetSdkVersion 30

Intune app wrapping tool 
    Version of the wrapper -(1.0.3610.6- latest one)
    Platform is your app based in (Java - android native)
    Package successfully login no response

**Intune app wrapping tool Steps **

STEP 1
------------------------------------------------------------------------->

Open windows powershell

run following-->
Import-Module "C:\Program Files (x86)\Microsoft Intune Mobile Application Management\Android\App Wrapping Tool\IntuneAppWrappingTool.psm1"

STEP 2
------------------------------------------------------------------------->

invoke-AppWrappingTool -InputPath C:\intne\testApp.apk -OutputPath C:\intune\testApp_wrapped-unsigned.apk -Verbose

STEP 3
------------------------------------------------------------------------->

Go to build-tools path D:\Android\Sdk\build-tools\30.0.3 ,
open cmd --->

zipalign -v -p 4 "C:\intune\testApp_wrapped-unsigned.apk" "C:\intune\testApp_wrapped-unsigned-aligned.apk"

STEP 4
------------------------------------------------------------------------->

apksigner sign --ks "C:\intune\test.jks" -ks-pass pass:test --ks-key-alias test --out "C:\intune\testApp_wrapped-signed.apk" "C:\intune\testApp_wrapped-unsigned-aligned.apk"

**Comment by bannus** [comment]
Hi @163shuai, thanks for the report.

1. Can you confirm that your app works as expected before applying the App Wrapping Tool?
2. Can you share more information about why you believe this to be caused by the App Wrapping Tool? Are there any runtime logs that point to an issue in the wrapping process?
3. Are you able to share your app or a simple project that can reproduce this issue?

**Comment by FAngelvs** [comment]
@bannus 
I might be having the same issue. 

Our app works fine when unwrapped, but wrapped one fails to run.

Start an app
Email and password is being requested with a usual MS login screen
I enter my credentials
Form is posted to the server and mobile phone displays full screen loading indicator. Blue one first and than it switches to green one. And it just endlessly shows that loading indicator like on the screenshot below. 


<img width="342" alt="image" src="https://user-images.githubusercontent.com/5345958/213758866-03777f1c-ec8d-43f3-ad26-137a994e1cb8.png">

**Comment by 163shuai** [comment]
@bannus 
App Wrapping Tool is OK until it is updated
Application download address : https://www.pgyer.com/Z0p7
The application is uploaded to the intune platform


![wapping-log](https://user-images.githubusercontent.com/89518550/215303027-907a24cb-985c-4d1c-953d-c9f719933e10.jpg)
[app-log.txt](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/10528869/app-log.txt)

**Comment by meghandaly** [comment]
@FAngelvs  and @163shuai Can y'all do us a favor and [collect the Company Portal logs](https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android) while reproducing the observed behavior?

**Comment by 163shuai** [comment]
@bannus 
The app-log.txt in the comments above is the log

**Comment by FAngelvs** [comment]
As it appeared, this looks to be resolved for us now. Our users got the latest version of the Company Portal app and everything works fine now.

**Comment by 163shuai** [comment]
@rygo-msft   I still can't log in here. Please check

[log.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/10751892/log.zip)

**Comment by rygo-msft** [comment]
@163shuai the logs indicate that your app has not been targeted for policy. Intune wrapped apps must be targeted for APP policy in order to use.
https://learn.microsoft.com/en-us/mem/intune/apps/app-protection-policies

**Comment by 163shuai** [comment]
After policy binding
I got the latest version of the company portal application and everything is fine now.
