### ISSUE TITLE
Unable to install on Android device

### ISSUE THREAD

**Issue by BBokdam** [msintuneappsdk/intune-app-wrapping-tool-android#8]
I wrapped an app for Android. This went succesful and also the upload an configuration of a policy in Intune was succesful.
The app is showing in the "Company portal" app.

But when I install the app on an Android device the installation failed without error and only stated, try again.

I tried this with and without a polcy configured, both have the same result.

I followed the manual that is provided with the download.

Can somebody help me with this?

**Comment by msintuneappsdk** [comment]
Hi @BBokdam, are you still experiencing this issue? Please send an email to msintuneappsdk@microsoft.com as we would need some more information from you to debug.

**Comment by BBokdam** [comment]
Hi msintuneappsdk, the problem was with the apk. I didn't receive the correct apk file from the supplier. 
Thanks for the following up.
