### ISSUE TITLE
Error while upload wrapped apk to manage google play

### ISSUE THREAD

**Issue by asher0pa** [msintuneappsdk/intune-app-wrapping-tool-android#82]
Hi.
We have in-house develop app.
When try to upload the app directly to manage Google play it work without errors.

When wrapping the same apk with the tool getting error while uploading:

`APK signature is invalid or does not exist. Error from apksigner: string_arg: "ERROR: JAR_SIG_NO_MANIFEST: Missing META-INF/MANIFEST.MF"`

Any idea what can cause the issue it happened on 2 different apps.

Tnx.

**Comment by meghandaly** [comment]
You need to re-sign your APK after running the App Wrapper, see [Reusing signing certificates and wrapping apps](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#reusing-signing-certificates-and-wrapping-apps).

If this does not resolve your issue, please reopen the issue and provide all details requested in the bug report template as Boyu requested.
