### ISSUE TITLE
Intune login error after warpping: AADSTS90020 -The SAML 1.1 Assertion is missing ImmutableID of the user.

### ISSUE THREAD

**Issue by JesseLiu1997** [msintuneappsdk/intune-app-wrapping-tool-android#83]
Describe the bug:
========================================================================
Our Mobile android App uses Azure AD for login & authentication. There is no problem with deploying the App to Intune without wrapping. But the login cannot be performed after wrapping, the user encounters an error when logging in. error message: **AADSTS90020-The SAML 1.1 Assertion is missing ImmutableID of the user.**
**more, using the ISO app packaged with the same react native source code, wrapping & deploying to Intune has no problem with user login.**

The current technical situation related to our android App is as follows:
It is developed using React Native technology, and does not use MSAL as the authentication library, but uses Oauth to directly call https://login.microsoftonline.com/${tenantId}/oauth2/v2.0/authorize to complete the authentication in the mobile browser, and then call back the App to complete the login.

Pipeline wrapping script:
========================================================================
  - stage: intune_wrap
    displayName: 'Wrap with intune'
    dependsOn: build
    jobs:
      - job: install_wrapping_tool
        displayName: 'Prepare Intune wrapping tool'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: none

          - script: git clone --branch 1.0.3401.4 https://github.com/msintuneappsdk/intune-app-wrapping-tool-android.git intune_wrapping_tool
            displayName: 'Checkout wrapping tool'
            workingDirectory: $(Pipeline.Workspace)

          - script: |
              unzip InstallAWT.exe
              unzip InstallAWTCore.exe || true
            displayName: 'Extract wrapping tool'
            workingDirectory: $(Pipeline.Workspace)/intune_wrapping_tool

          - script: |
              cp IntuneAppWrappingTool.psm1 $(Build.ArtifactStagingDirectory)
              cp -r lib $(Build.ArtifactStagingDirectory)
            displayName: 'Copy files'
            workingDirectory: $(Pipeline.Workspace)/intune_wrapping_tool

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: intune-wrapping-tool

      - job: intune_wrap
        displayName: 'Wrap with Intune'
        dependsOn: install_wrapping_tool
        pool:
          vmImage: 'windows-latest'
        steps:
          - task: DownloadSecureFile@1
            name: keystorePath
            inputs:
              secureFile: $(keystoreFile)

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: $(artifactName)
              path: $(Build.SourcesDirectory)\$(artifactName)

          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: intune-wrapping-tool
              path: $(Build.SourcesDirectory)\intune-wrapping-tool

          - task: PowerShell@2
            displayName: 'Perform wraping'
            inputs:
              targetType: 'inline'
              script: |
                $keystorePassword = ConvertTo-SecureString "$(keystorePassword)" -AsPlainText -Force
                $keyaliasPassword = ConvertTo-SecureString "$(keyAliasPassword)" -AsPlainText -Force
                Import-Module $(Build.SourcesDirectory)\intune-wrapping-tool\IntuneAppWrappingTool.psm1
                Invoke-AppWrappingTool -InputPath $(Build.SourcesDirectory)\$(artifactName)\*.apk -OutputPath '$(build.artifactStagingDirectory)\$(Build.SourceVersion)-$(buildSuffix)_wrapped.apk' -KeyStorePath $(keystorePath.secureFilePath) -KeyStorePassword $keystorePassword -KeyAlias $(keyAliasName) -KeyPassword $keyaliasPassword
              workingDirectory: $(Pipeline.Workspace)

          - task: AndroidSigning@3
            inputs:
              apkFiles: '$(build.artifactStagingDirectory)\$(Build.SourceVersion)-$(buildSuffix)_wrapped-unsigned.apk'
              apksignerKeystoreFile: '$(keystoreFile)'
              apksignerKeystorePassword: '$(keystorePassword)'
              apksignerKeystoreAlias: '$(keyAliasName)'
              apksignerKeyPassword: '$(keyAliasPassword)'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'mv "$(build.artifactStagingDirectory)\$(Build.SourceVersion)-$(buildSuffix)_wrapped-unsigned.apk" "$(build.artifactStagingDirectory)\$(Build.SourceVersion)-$(buildSuffix)_wrapped.apk"'

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: $(artifactName)-wrapped

**wrap successfully:**
![16848053319131](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/24383252/239df2d3-d8c5-4049-a8a0-fd1e5f1d4b11)

Issue/Bug screenshots and logs:
========================================================================
![20230519173108](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/24383252/b712dd30-bf46-470d-9498-44fa49c15b2b)

Expected behavior:
========================================================================
Deploying the app to Intune without wrapping has been successful and no issues have been encountered. 
We hope that the same smooth login can be achieved after wrapping the app.

**any idea about the problem? It is very urgent and needs to be resolved as soon as possible.**

**Comment by meghandaly** [comment]
@JesseLiu1997 

The methodology you describe for invoking the App Wrapper is not in accordance with the documented methodology for [Installing the App Wrapper](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#install-the-app-wrapping-tool) and [Running the App Wrapper](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#run-the-app-wrapping-tool).

Any invocation that veers from the official documentation is not considered a supported scenario. When wrapping your application, please follow the steps outlined in the linked documentation.

Regarding the authentication error, the [reference documentation](https://learn.microsoft.com/azure/active-directory/develop/reference-error-codes) states:

> AADSTS90020 | The SAML 1.1 Assertion is missing ImmutableID of the user. Developer error - the app is attempting to sign in without the necessary or correct authentication parameters.
-- | --

and we would require additional information to identify a root cause. 

If the error persists after wrapping your app following the instructions, please [capture the CP logs](https://docs.microsoft.com/mem/intune/user-help/send-logs-to-microsoft-android) and share the incident ID.

**Comment by JesseLiu1997** [comment]
@meghandaly 
Thanks for your feedback.
I added the information of Pipeline wrapping script, you can see that the steps here completely follow Microsoft's guide; and finally the android app has been wrapped successfully.
The problem now is that the app cannot log in after wrapping, and it is completely normal without wrapping, so it must be because of wrapping that the login process of this android app becomes abnormal.

**Comment by meghandaly** [comment]
@JesseLiu1997 

As previously requested, please [capture the CP logs](https://docs.microsoft.com/mem/intune/user-help/send-logs-to-microsoft-android) and share the incident ID while reproducing the issue.

Without that information we are unable to provide additional insights.

**Comment by NoahHuang2023** [comment]
@meghandaly Hi, I am Jesse's colleague, we not specified the version when Git clone the wrapping tool, as I understanding, it gets the latest version of tool, right?
![image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/38906053/49a7513a-5560-4495-b40d-6290cb1bc2fa)

the App could wrapped successful and deployed to testing intune env, but after I open the wrapped app and input my account then click login
![image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/38906053/83a851a3-69ea-47e1-9528-d09c08b4aa1f)
I will get below error:
Request ID: c259eae0-0f72-40e5-8ed2-a6ae610ab100
Correlation ld: ba629fcd-8ceb-4f61-8258-9918f6f1357d
Timestamp:2023-06-01T09:40:21Z
Incident ID: YA3C6RC3
![image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/38906053/5e32de0b-da9f-4086-9bb6-9548c6a579d9)
![image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/38906053/4a369ffc-3546-449c-a72c-99a416e55018)

For unwrapped app, after input my account then click login, it could go to "Choose the authentication chain" page, and after I input the one time password, I can login successful
![image](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/38906053/96efd3a2-6721-4cbc-8f38-0e20b6201de3)

Could you help check with this incident id?

**Comment by rygo-msft** [comment]
Hi, we haven't heard from you in a few months. I am closing this issue as stale. If you are still experiencing this issue, please reopen the issue and provide the requested details.
