### ISSUE TITLE
On launch crash of MAUI app after wrapping on android platform

### ISSUE THREAD

**Issue by PramodKumarHK89** [msintuneappsdk/intune-app-wrapping-tool-android#88]
**Questions to Ask Before Submission**
1. Does you app launch successfully without wrapping?
Yes, it does.
3. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping?
Yes. Followed all the instructions. 
5. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper)
No.
7. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues?
Yes. But this is specific to app wrapping tool I believe 
9. Are you using the latest version of the App Wrapper?
Yes . that latest one. 

**Describe the bug:**
I have wrapped the .NET MAUI apk using latest app wrapping tool. It is able to install the app on the device. It crashes on launch. If I uninstall the company portal afte installing my sample app then, app says "please install Company portal". It appears like, app is crashing while it is establising connection with broker(COmpany portal)

**To Reproduce**
1. Create a sample  MAUI app. 
2. Wrapp the apk and sign the spk and upload it to Intune admin portal
3. Applye MAM policy
4. App simply crashes

**Expected behavior:**
App should launch and MAM should apply 
 
INCIDENT ID - SF6DY23R

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 8
 - OS Version: [Android 12]

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
-Latest
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
-MAUI

**Additional context:**

**Comment by rygo-msft** [comment]
Hi @PramodKumarHK89, the App Wrapping Tool does not support MAUI apps. You should leverage the MAUI SDK directly instead. https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android
