### ISSUE TITLE
Version details mentioned incorrectly

### ISSUE THREAD

**Issue by Anusha-ACN** [msintuneappsdk/intune-app-wrapping-tool-android#9]
Hi Team,
Please check the release version which you have mentioned in GitHub (**Version 1.02022.1**) .
The actual version shown as (**1.0.2022.1**) while performing the wrapping process
![wrapper_version](https://user-images.githubusercontent.com/32734340/33113459-77026d82-cf7e-11e7-9884-3fbe0f329dd2.png)
Note: 
Due to incorrect version we are unable to find the release notes for **1.0.2022.1** in Github
https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/releases/

This is not a major issue but notifying you for correcting the statement. 
Thank you.

**Comment by msintuneappsdk** [comment]
Thanks for pointing this out - there was an extra 0 in the version name in the Readme for this repo. It has been fixed and a release tag has been added. Closing item.
