### ISSUE TITLE
[UPDATE App target: 34] Support Android 14

### ISSUE THREAD

**Issue by milaptank** [msintuneappsdk/intune-app-wrapping-tool-android#90]
## Information
Update App target: 34, to Support Android 14
### Feature Request

Failed to package app. com.microsoft.intune.mam.apppackager.utils.AppPackagerException: This app's target API level is above the MAM target API level. App target: 34, MAM target: 33. Please upgrade to the newest version of the App Wrapping Tool if available.

Application is Crashing on Android 14 after MAM wrap

**Comment by rygo-msft** [comment]
Targeting support is now available in version 1.0.4191.6
