### ISSUE TITLE
Expo React native wrapped app keeps stopping

### ISSUE THREAD

**Issue by sonuchandra2010** [msintuneappsdk/intune-app-wrapping-tool-android#92]
I have an expo react-native android application
The application was built using expo build tools.

I downloaded the apk from expo, wrapped using the latest wrapping tool - wrapping is successful.
I see the below
The application was successfully wrapped.
Please zipalign and sign the application before use.

Then signed it
tried with manual signing. used https://github.com/patrickfav/uber-apk-signer , as well as google play signing.

The app installs but as soon as it is launched, it stops

I see error "app_name keeps stopping"

Are expo react native apps supported by the intune wrapping tool?

The app successfully launches without wrapping

When trying to install the wrapped app without signing the below error is seen
"App is not installed as package appears to be invalid"

 - Device:Samsung Galaxy S23
 - OS Version: Android 13

**Comment by Staceadam** [comment]
We have been having a similar issue with our Intune wrapped app on Samsung Galaxy devices and Android 13. Curious if you were able to resolve the issue. Also what version of react-native and (if applicable) what version of react-native-reanimated?
