### ISSUE TITLE
Android wrapper (1.0.4191.6) is not copying assets

### ISSUE THREAD

**Issue by chester23491** [msintuneappsdk/intune-app-wrapping-tool-android#93]
**Questions to Ask Before Submission**
1. Does you app launch successfully without wrapping?
**>> Yes**
2. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping?
**>> Yes**
3. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper)
**>> No**
4. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues?
**>> Yes, but didn't found any related issues.**
5. Are you using the latest version of the App Wrapper?
**>> Yes, with 1.0.4191.6**

**Describe the bug:**
Our wrapped app doesn't contain any assets after wrapping with the new version of android wrapper (1.0.4191.6). When the app is wrapped with the version (1.0.3935.1) the assets are available. Without the assets the app cannot start successfully.

**To Reproduce**
1. Wrap app with the new wrapper and old wrapper
2. Compare assets folder
3. See error: Assets folder with the new wrapper only contains file `com.microsoft.intune.mam.MAMMethodRewrites.txt`.

**Expected behavior:**
The new wrapper should also include the assets folder.

**Screenshots and logs:**

![Screenshot 2023-11-07 at 07 47 54](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/assets/22290769/a4dd00bc-a1a3-48e2-8be7-b91dd64d7c43)

[verbose-log-1.0.4191.6.log](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/13217671/verbose-log-1.0.4191.6.log)

[verbose-log-1.0.3935.1.log](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/13217675/verbose-log-1.0.3935.1.log)

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS Version: Android 13

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version?
**>> Yes, with 1.0.4191.6**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
**>> Flutter**
- For pre-wrapping errors, does the app build without being wrapped?
- For post-wrapping errors, does the app launch without being wrapped?
- **>> Yes**
- Who is the customer?
**>> Confident**
- Do you see a trend with it only being reproduced on a specific device?
**>> Can be reproduced an all devices**

**Additional context:**
- Shall we open a Microsoft Support ticket for this issue?

- Edited on 7.11.2023 due wrong screenshot (I compared the the wrapped and unwrapped application), sorry!

**Comment by boyzhang-msft** [comment]
Hi @chester23491 , thanks for reporting this issue. We have opened a bug on our side and are actively working on it. There is no ETA at the moment, but I'll keep this thread updated once we have a fix validated.

**Comment by chester23491** [comment]
@boyzhang-msft Thank you! I reviewed my issue and found a error I did. Today I replaced the screenshot of the APK comparison. By mistake I was comparing the wrapped app with the unwrapped app. Sorry for any inconvenience!

**Comment by rygo-msft** [comment]
This issue should now be fixed by version 1.0.4214.3

**Comment by maheshwarimrinal** [comment]
I am facing same issue in the latest version
