### ISSUE TITLE
Latest APK wrap gives an invalid apk file.

### ISSUE THREAD

**Issue by E-N-G-XOR** [msintuneappsdk/intune-app-wrapping-tool-android#95]
**Questions to Ask Before Submission**
1. Does you app launch successfully without wrapping? YES
2. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping? YES
3. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper) NO
4. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues? YES
5. Are you using the latest version of the App Wrapper? YES

**Describe the bug:**
A clear and concise description of what the bug is. intunes says the app is successfully wrapped, but it is not. I have an apk I cannot use.

```
The package name for this app is 'app_name'. If you need to specify the package name during deployment, please use this one.
The application was successfully wrapped.
Please zipalign and sign the application before use.
```

**To Reproduce**
1.  simply install the latest tooling from git. 
2. import the module 
4.  invoke-AppWrappingTool -InputPath .\in.apk -OutputPath  .\out.apk -Verbose | Tee-Object -FilePath .\wrap.log

**Expected behavior:**

app to launch and work as per  pre-wrapping

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is crashing post-wrapping, do you have app logs for the crash itself? Attached below
- If your app is crashing pre-wrapping, do you have app logs for the wrapper errors?  app works fine pre-wrapping... (attached pre-wapping.jpg)

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel 6] Samsung Note 22 Ultra
 - OS Version: [e.g. Android 13]  Android 14

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? Latest
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Cordova
- For pre-wrapping errors, does the app build without being wrapped? NO
- For post-wrapping errors, does the app launch without being wrapped? NO
- Who is the customer? Me
- Do you see a trend with it only being reproduced on a specific device? No, Tried serveral android devices Note 22. 

**Additional context:**
[wrap.log](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/13875388/wrap.log)

Log says the app is successfully wrapped, but the app will not install on devices...  Error attached.
log

**Comment by sabaricod** [comment]
did you found any fix @E-N-G-XOR

**Comment by E-N-G-XOR** [comment]
Hi,

Not yet. The Microsoft guys think it has to with the fact that it is a
self-signed cert.

The tests continue...

Ta,
X

**Comment by E-N-G-XOR** [comment]
So, found the solution...

The problem is with the apk file.

So, once the apk file is signed and intune wrapped.

We then have to zipalign and  re-sign the apk (again) with with any
self-signed cert located in a keystore file with apksigner.

I used android studio to generate a dumpy keystore file and signed the
second time with that.

And we are business...

**Comment by rygo-msft** [comment]
To clarify, any modification to app file will break app signing (it wouldn't be a very good signature if it didn't detect modification). As such, all apk files created by the wrapper will be unsigned and must be zip-aligned and signed before use.

You do not need to sign apks with multiple keys, but signing _must_ be the last modification to an app for the signature to be valid.
