### ISSUE TITLE
Unable to retrieve App config key values in the wrapped App

### ISSUE THREAD

**Issue by naveentds** [msintuneappsdk/intune-app-wrapping-tool-android#97]
**Questions to Ask Before Submission**
1. Does you app launch successfully without wrapping? Yes
2. Have you reviewed the [prerequisites](https://learn.microsoft.com/mem/intune/developer/app-wrapper-prepare-android#fulfill-the-prerequisites-for-using-the-app-wrapping-tool) for App Wrapping? Yes
3. Does your issue have a solution in the [Troubleshooting Guide?](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/wiki/Troubleshooting-the-App-Wrapper) No 
4. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for similar issues? Yes
5. Are you using the latest version of the App Wrapper? Yes

**Describe the bug:**
Unable to retrieve the App config key values in the Intune wrapped LOB Android 
[CompanyPortalLogs.zip](https://github.com/msintuneappsdk/intune-app-wrapping-tool-android/files/14412162/CompanyPortalLogs.zip)
App.  
It looks like the App config key value pairs are set as per the Company Portal logs:
```
"ApplicationConfigurations": [
	        {
	            "ApplicationConfiguration": [
	                {
	                    "Value": "value1",
	                    "Name": "key1"
	                }
	            ]
	        }
	    ]
```
Please find the Company portal logs in the attachment for reference.
We use the following API to retrieve key value pairs in the Android App:
```
RestrictionsManager myRestrictionsMgr = (RestrictionsManager) ctx.getSystemService(Context.RESTRICTIONS_SERVICE);
Bundle restrictions = myRestrictionsMgr.getApplicationRestrictions();
```

We are not receiving the value for the key 'key1' in the App :
`String loginHint = restrictions.getString("key1");`
The value for loginHint is null.

Can you let us know if the above way to retrieve the App config key value pairs is correct or do you have any other way to retrieve the key values from ApplicationConfigurations in the App without using Intune SDK(we use Intune App wrapping tool)?

We also have filed a ticket with Intune support team. Please find the ticket # for reference.
'App configuration not reflecting - TrackingID#2402130010003351'.

**To Reproduce**
1. Set Application Config key values in Intune Admin portal. 
2. Create wrapped apk using Intune App Wrapping Tool.
3. Publish the wrapped LOB App in the Intune Admin portal.
4. The Application Config values are not retrieved in the App. 

**Expected behavior:**
The Application Config values should be retrieved in the App.
restrictions.getString("key1") should return the value 'value1', the value that is set in the Intune Admin portal.

**Screenshots and logs:**
- Logs attached.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS Version: Android 10

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? We are using latest wrapper version.
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Kotlin. Native Android App.
- For pre-wrapping errors, does the app build without being wrapped? Yes.
- For post-wrapping errors, does the app launch without being wrapped? Yes.
- Who is the customer? DocuSign
- Do you see a trend with it only being reproduced on a specific device? No.

**Additional context:**

**Comment by naveentds** [comment]
@ChismanRaheem Please let us know if there is any update on this issue.

**Comment by ChismanRaheem** [comment]
HI @naveentds  I'm currently examining case number 2402130010003351 and collaborating with our team internally on this matter. I'll provide an update as we progress with our investigation and have more information to share.

**Comment by meghandaly** [comment]
This is not a supported scenario for the App Wrapper. Please review our documentation, specifically: [ Does my application have or need App Configuration settings?](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1#does-my-application-have-or-need-app-configuration-settings)
